### ISSUE TITLE
登录报401

### ISSUE THREAD

**Issue by superjoo** [CarGuo/GSYGithubAppFlutter#105]
申请了Oauth apps，按照步骤配置到了项目中，登录时一直报401，求解
<img width="1110" alt="ate" src="https://user-images.githubusercontent.com/1567417/47782120-6957bf00-dd3a-11e8-8282-c2dca1d17dcf.png">

**Comment by superjoo** [comment]
已解决:)

**Comment by snaigle** [comment]
怎么解决的？

**Comment by CarGuo** [comment]
@superjoo 请看readme

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/111
