### ISSUE TITLE
申请了github oauth ,登录提示报错401，是我哪里设置有点问题吗？

### ISSUE THREAD

**Issue by caihong0622** [CarGuo/GSYGithubAppFlutter#111]
![simulator screen shot - iphone xs max - 2018-11-06 at 13 44 57](https://user-images.githubusercontent.com/42528447/48045172-28dcc300-e1ca-11e8-9aeb-73222a3e70c9.png)

**Comment by caihong0622** [comment]
等待了一会就好了·······

**Comment by snaigle** [comment]
有2fa验证时，账号密码正确也会提示401

**Comment by CarGuo** [comment]
是的，两步认证没做支持 @snaigle

**Comment by wcmbeta** [comment]
[2fa参考](https://developer.github.com/v3/auth/#working-with-two-factor-authentication)

**Comment by CarGuo** [comment]
@wcmbeta 我知道2fa实现，但是要增加测试功能的时候，发现不支持中国+86号码

**Comment by lfp90** [comment]
我扫描下载了安卓的apk也是一个问题
