### ISSUE TITLE
Weex,RN,Flutter这三个作者认为哪个最适合学习

### ISSUE THREAD

**Issue by caihong0622** [CarGuo/GSYGithubAppFlutter#113]
我看作者写了用这三个都写了这个项目，对这几个最大的感受是什么。

**Comment by CarGuo** [comment]
https://www.jianshu.com/p/7e0bd4708ba7  你可以看看，大致了解下。
目前三个平台，个人觉得 weex 适合适当了解，毕竟vue的模式稍微学习下，用到快应用开发或者小程序开发也行。
RN适合投入去做项目现在， 毕竟比较成熟了。
Flutter目前更适合做练手。
