### ISSUE TITLE
iOS 版本 TextField 输入中文时 bug

### ISSUE THREAD

**Issue by lukailun** [CarGuo/GSYGithubAppFlutter#116]
iOS 系统下登录页面用户名 TextField 输入中文拼音过程中，点击密码 TextField 获取焦点，程序闪退。
推测应该是 Flutter 自身 TextField 的 bug。
![bug](https://user-images.githubusercontent.com/20470157/48199504-31362900-e397-11e8-93b8-b1be8766df55.png)

**Comment by CarGuo** [comment]
收到

**Comment by mindfocus** [comment]
另外一个问题也跟登陆有关，华为P10密码键盘遮挡输入框
 @CarGuo

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/132

**Comment by dishcheng** [comment]
现在还是有这个问题啊...

**Comment by jackgitsource** [comment]
请问这个问题解决了吗
