### ISSUE TITLE
dart-analysis 有异常

### ISSUE THREAD

**Issue by snaigle** [CarGuo/GSYGithubAppFlutter#118]
环境  flutter 0.10.2  dart: 2.1.0  , macos 10.14.1
在idea下 dart-analysis 提示
error: The argument type 'List<OneSequenceGestureRecognizer>' can't be assigned to the parameter type 'Set<Factory<OneSequenceGestureRecognizer>>'. (argument_type_not_assignable at [gsy_github_app_flutter] lib/widget/webview/WebView.dart:79)

直接用flutter run 是可以成功运行的

**Comment by CarGuo** [comment]
那是因为with会有错误警告，可暂时忽略使用// ignore: mixin_inherits_from_not_object

而WebView是因为 AndroidView的使用的 flutter sdk版本不同，已经升级支持新版本0.11.3
