### ISSUE TITLE
在账号或密码框，长按准备粘贴时app会崩溃

### ISSUE THREAD

**Issue by snaigle** [CarGuo/GSYGithubAppFlutter#120]
android app， 提示  ```Another exception was thrown: NoSuchMethodError: The getter 'pasteButtonLabel' was called on null.```

**Comment by CarGuo** [comment]
新flutter  sdk 更新后导致的，主要是因为以前主题中增加
```
  platform: TargetPlatform.iOS//滑动返回
```

去掉就正常了，目前使用 `CupertinoPageRoute` 实现页面滑动返回
