### ISSUE TITLE
在网易MUMU模拟器里运行不起来

### ISSUE THREAD

**Issue by ieras** [CarGuo/GSYGithubAppFlutter#121]
看来 这是网易mumu模拟器的问题了～
![image](https://user-images.githubusercontent.com/17443060/48478069-346d6100-e83e-11e8-9494-9c18815701a1.png)

**Comment by CarGuo** [comment]
额，模拟器就不清楚了

**Comment by ieras** [comment]
可能网易mumu模拟器 的锅吧  看错误提升 是 启动 dart vm失败

**Comment by jp1017** [comment]
https://github.com/flutter/flutter/issues/21988#issuecomment-536243610 解决了
