### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by liuyehua** [CarGuo/GSYGithubAppFlutter#149]
flutter首页几个屏侧滑滚动的时候，页面抖动十分明显，就是掉帧，好几个app都是这样，flutter这点坑了

**Comment by CarGuo** [comment]
目前因为我这边是从网络获取数据后存库才渲染，而dart只是单线程多异步处理。
其实可以优化下，这一块可以放到新的flutter io线程去出去，只是麻烦一些。类似的情况还有滑动时每个页面的渲染时机控制，其实属于应用在某些地方没有做优化的，我认为。
