### ISSUE TITLE
报错了，求助

### ISSUE THREAD

**Issue by 252162875** [CarGuo/GSYGithubAppFlutter#161]
* Error running Gradle:
ProcessException: Process "C:\Users\Administrator\Desktop\GSYGithubAppFlutter-master\android\gradlew.bat" exited abnormally:

> Configure project :flutter_statusbar

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_statusbar'.
> Could not resolve all artifacts for configuration ':flutter_statusbar:classpath'.
   > Could not find lombok-ast.jar (com.android.tools.external.lombok:lombok-ast:0.2.3).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command: C:\Users\Administrator\Desktop\GSYGithubAppFlutter-master\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by CarGuo** [comment]
看不出什么问题，看下Flutter statusbar是否正常安装

**Comment by 252162875** [comment]
![image](https://user-images.githubusercontent.com/18607783/49919447-9672c200-fee1-11e8-9bb6-d2f9832ea97d.png)
安装了，它老提示我https://jcenter.bintray.com/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.jar这个找不到

**Comment by 252162875** [comment]
这是错误信息
![image](https://user-images.githubusercontent.com/18607783/49919631-2b75bb00-fee2-11e8-88ff-e1356fd87a48.png)

**Comment by CarGuo** [comment]
看起来是jcenter同步没同步成功

**Comment by 252162875** [comment]
是墙的缘故吗？指导一下怎么处理~~~

**Comment by CarGuo** [comment]
在android目录下执行下 ./gradlew  build 看看

**Comment by 252162875** [comment]
执行过程中报这个了，是我Build Tools版本太低吗？我先升级一下试试
![_20181213165416](https://user-images.githubusercontent.com/18607783/49927027-01c78e80-fef8-11e8-9daf-825f1bdf1e9d.png)

**Comment by CarGuo** [comment]
感觉你像是请求不到jcenter
