### ISSUE TITLE
Error running Gradle

### ISSUE THREAD

**Issue by quinnQjc** [CarGuo/GSYGithubAppFlutter#171]
![0 cb 16 t3jjxwq qangc8](https://user-images.githubusercontent.com/45277972/50075265-672dbf00-0219-11e9-8cfe-0055c5b7b239.png)

请问为啥我加了阿里的镜像了还是报这个错呢

**Comment by quinnQjc** [comment]
> 这个是gradle这个打包的时候，从jcenter同步的jar包失败

那请问这个该怎么办呢, 或者说类似的问题如何处理呢, 我经常遇到这样的问题,,,麻烦解答一下, 感激不尽

**Comment by CarGuo** [comment]
一般翻墙或者换个网络环境就可以，因为一般jcenter是不需要翻墙的。

可以配置 全局的 gradle.properties  文件增加代理，或者是不是gradle 配置了离线

**Comment by quinnQjc** [comment]
> 一般翻墙或者换个网络环境就可以，因为一般jcenter是不需要翻墙的。
> 
> 可以配置全局的gradle.properties文件增加代理，或者是不是gradle配置了离线
![0 40bcj 3pp bucymksnc](https://user-images.githubusercontent.com/45277972/50136137-b6372b00-02d1-11e9-8cc3-3321feef4517.png)

呃设置代理了也不行耶...我已经开了蓝灯了的...求助
