### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by songshitong** [CarGuo/GSYGithubAppFlutter#186]
红米note4搜索长按粘贴，报红，pastebuttonlabel  was called  on  null

**Comment by CarGuo** [comment]
下载的apk 试试会不会

![](https://raw.githubusercontent.com/CarGuo/GSYGithubAppFlutter/master/download.png)

https://www.pgyer.com/vj2B

**Comment by songshitong** [comment]
![Uploading image.png…]()
还是不行

**Comment by CarGuo** [comment]
图片没传上来，我这边测试红米5plus mui10.1 正常

**Comment by CarGuo** [comment]
奇怪，我这边没复现问题，以前有出现过，但是升级sdk后正常了

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/120

**Comment by CarGuo** [comment]
fix

**Comment by GanZhiXiong** [comment]
我这里也出现了这个问题
使用机型iPhone 8 plus
我创建了一个文本框，在文本框中长按就会出现songshitong发送图片的问题，登录界面你的文本框中长按是不会出现的。
我的代码如下:
` Widget _erpUrlContainer() {
    return new Container(
        child: new TextFormField(
//            focusNode: _focus,
            autofocus: true,
            controller: erpUrlController,
            decoration: InputDecoration(
                suffixIcon: new Icon(
                  Icons.cloud_circle,
                  color: Theme.of(context).primaryColor,
                ),
                labelText: "ERP地址",
                labelStyle: TextStyle(fontSize: 18.0)),
            keyboardType: TextInputType.url),
        margin: EdgeInsets.only(bottom: 5.0));
  }
`

**Comment by JWong1105** [comment]
> fix

你好，这个问题在我的demo里也出现了，是什么原因导致的呢，能回复一下吗，谢谢

**Comment by CarGuo** [comment]
@JWong1105


https://github.com/CarGuo/GSYGithubAppFlutter/commit/97b2d53b627ff9ca41314a7a852bf39ed5d18b8f

一般就是主题和语言delegate等引起的

**Comment by JWong1105** [comment]
> @JWong1105
> 
> [97b2d53](https://github.com/CarGuo/GSYGithubAppFlutter/commit/97b2d53b627ff9ca41314a7a852bf39ed5d18b8f)
> 
> 一般就是主题和语言delegate等引起的

好的，谢谢~

**Comment by JWong1105** [comment]
好的，谢谢！

**Comment by JWong1105** [comment]
@CarGuo 谢谢~
