### ISSUE TITLE
oauth key and password were set, but App throw Error 442 when i try to  login?How can I fix it?

### ISSUE THREAD

**Issue by zsmjhtn** [CarGuo/GSYGithubAppFlutter#187]
when I open **url: https://api.github.com/authorizations** in safari:
params like this:
{"scopes":["user","repo","gist","notifications"],"note":"admin_script","client_id":"xxxxx","client_secret":"xxxx"}

{
  "message": "API rate limit exceeded for 61.175.197.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}

**Comment by zsmjhtn** [comment]
emmmm...... Suddenly,sign in successly when I debugging the app. 
it is 4:00 afternoon.
Maybe the  rate limit will be recovered every hour.
But how to solve it?

**Comment by CarGuo** [comment]
if  ` "client_id":"xxxxx","client_secret":"xxxx"` is right ,
you will not face to API rate limit 
![](https://raw.githubusercontent.com/CarGuo/GSYGithubAppFlutter/master/register1.jpg)
