### ISSUE TITLE
新版本登录报401，已经正确而设置了CLIENT_ID和CLIENT_SECRET

### ISSUE THREAD

**Issue by manburenshenglu** [CarGuo/GSYGithubAppFlutter#191]

**Comment by CarGuo** [comment]
是否设置了两步认证？

**Comment by manburenshenglu** [comment]
楼主，怎么做两步认证？请明示一下，我小白，readme中没找到，谢谢

**Comment by CarGuo** [comment]
不是，如果没设置过两部认证的，那应该没问题。
https://github.com/CarGuo/GSYGithubAppFlutter/issues/111

**Comment by manburenshenglu** [comment]
#111 的问题我看了，但还是不太明白：设置两步认证怎么操作？我是今天从github上把你的源码拉下来的，之前的源码好像没有这个问题

**Comment by manburenshenglu** [comment]
我没有开启两步认证

**Comment by manburenshenglu** [comment]
![dddd](https://user-images.githubusercontent.com/13146756/50389851-4bbb3a80-076a-11e9-87cd-8ad7889ec86e.png)

**Comment by CarGuo** [comment]
111  主要是说，申请appid后要稍等一段时间

**Comment by manburenshenglu** [comment]
谢谢楼主，现在可以了

**Comment by wcnmtx** [comment]
原来是用户名 我一直用邮箱号去 登录 ，难怪一直配置正确也是401
