### ISSUE TITLE
关于redux的一个比较急的问题

### ISSUE THREAD

**Issue by qq326646683** [CarGuo/GSYGithubAppFlutter#198]
一个页面下拉刷新，其他被StoreBuilder包着的页面都会执行build，大量重复渲染怎么解决啊？？

**Comment by qq326646683** [comment]
我在A页面dispatch改变B页面的数据，结果被StoreBuilder的页面都build了一遍。。。

**Comment by CarGuo** [comment]
额，我这么看也不好说，主要是shying你的地方不要绑定整个store，更新时也仅更新store内的某个对象

**Comment by qq326646683** [comment]
还请大神能把一个store拆分开，做到dispatch后只build用到改变的数据的地方，解决dispatch后所有页面都build的问题，万分感谢🙏
