### ISSUE TITLE
Error happen when build. Only with iOS

### ISSUE THREAD

**Issue by letruonglamit** [CarGuo/GSYGithubAppFlutter#204]
I have issue when build iOS

I receive a debug console below: 
> Launching lib/main.dart on iPhone XR in debug mode...
> Warning: CocoaPods recommended version 1.5.0 or greater not installed.
> Pods handling may fail on some projects involving plugins.
> To upgrade:
>   brew upgrade cocoapods
>   pod setup
> 
> Xcode build done.                                           14.7s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
> ** BUILD FAILED **
> Xcode's output:
> ↳
> === BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Debug ===
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "Headers/permission_handler-umbrella.h"
> ^
> /Users/lelam/WorkSpaceFlutter/GSYGithubAppFlutter/ios/Pods/Target Support Files/permission_handler/permission_handler-umbrella.h:13:9: error: include of non-modular header inside framework module 'permission_handler': '/Users/lelam/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.0.0/ios/Classes/PermissionHandlerPlugin.h'
> #import "PermissionHandlerPlugin.h"
> ^
> <unknown>:0: error: could not build Objective-C module 'permission_handler'
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "Headers/permission_handler-umbrella.h"
> ^
> /Users/lelam/WorkSpaceFlutter/GSYGithubAppFlutter/ios/Pods/Target Support Files/permission_handler/permission_handler-umbrella.h:13:9: error: include of non-modular header inside framework module 'permission_handler': '/Users/lelam/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.0.0/ios/Classes/PermissionHandlerPlugin.h'
> #import "PermissionHandlerPlugin.h"
> ^
> <unknown>:0: error: could not build Objective-C module 'permission_handler'
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "Headers/permission_handler-umbrella.h"
> ^
> /Users/lelam/WorkSpaceFlutter/GSYGithubAppFlutter/ios/Pods/Target Support Files/permission_handler/permission_handler-umbrella.h:13:9: error: include of non-modular header inside framework module 'permission_handler': '/Users/lelam/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.0.0/ios/Classes/PermissionHandlerPlugin.h'
> #import "PermissionHandlerPlugin.h"
> ^
> <unknown>:0: error: could not build Objective-C module 'permission_handler'
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "Headers/permission_handler-umbrella.h"
> ^
> /Users/lelam/WorkSpaceFlutter/GSYGithubAppFlutter/ios/Pods/Target Support Files/permission_handler/permission_handler-umbrella.h:13:9: error: include of non-modular header inside framework module 'permission_handler': '/Users/lelam/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.0.0/ios/Classes/PermissionHandlerPlugin.h'
> #import "PermissionHandlerPlugin.h"
> ^
> <unknown>:0: error: could not build Objective-C module 'permission_handler'
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "Headers/permission_handler-umbrella.h"
> ^
> /Users/lelam/WorkSpaceFlutter/GSYGithubAppFlutter/ios/Pods/Target Support Files/permission_handler/permission_handler-umbrella.h:13:9: error: include of non-modular header inside framework module 'permission_handler': '/Users/lelam/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.0.0/ios/Classes/PermissionHandlerPlugin.h'
> #import "PermissionHandlerPlugin.h"
> ^
> <unknown>:0: error: could not build Objective-C module 'permission_handler'
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "Headers/permission_handler-umbrella.h"
>^
> <unknown>:0: error: could not build Objective-C module 'permission_handler'
> Could not build the application for the simulator.
> Error launching application on iPhone XR.
> Exited (sigterm)

Flutter doctor: 

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-US)
> [!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> [!] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     ! CocoaPods out of date (1.5.0 is recommended).
>         CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin
>         usage on the Dart side.
>         Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
>         For more info, see https://flutter.io/platform-plugins
>       To upgrade:
>         brew upgrade cocoapods
>         pod setup
> [✓] Android Studio (version 3.2)
> [✓] VS Code (version 1.30.1)
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 2 categories.

**Comment by CarGuo** [comment]
plugin  permission_handler

**Comment by letruonglamit** [comment]
How to fix this issue?

**Comment by CarGuo** [comment]
find permission_handler  is it installed?
