### ISSUE TITLE
你好 dart sdk找不到？

### ISSUE THREAD

**Issue by jj89757hhb** [CarGuo/GSYGithubAppFlutter#215]
![dart sdk](https://user-images.githubusercontent.com/957927/50875696-7d87fe80-1404-11e9-8043-9ae19b37e92f.png)

**Comment by CarGuo** [comment]
安装好dart 和flutter 的plugin插件，然后指向你本地的dart SDK就好了，一般dart sdk都flutter SDK的 cache里

**Comment by jj89757hhb** [comment]
谢谢看到了！sdk 原来是选择里面的子目录
但是编译还是错误：
Error: Could not resolve the package 'flutter' in 'package:flutter/cupertino.dart'.
Error: Could not resolve the package 'flutter' in 'package:flutter/foundation.dart'.
Error: Could not resolve the package 'flutter' in 'package:flutter/material.dart'.
Error: Could not resolve the package 'event_bus' in 'package:event_bus/event_bus.dart'.
Error: Could not resolve the package 'flutter_localizations' in 'package:flutter_localizations/flutter_localizations.dart'.
Error: Could not resolve the package 'fluttertoast' in 'package:fluttertoast/fluttertoast.dart'.
Error: Could not resolve the package 'gsy_github_app_flutter' in 'package:gsy_github_app_flutter/common/event/HttpErrorEvent.dart'.
Error: Could not resolve the package 'gsy_github_app_flutter' in 'package:gsy_github_app_flutter/common/localization/GSYLocalizationsDelegate.dart'.
Error: Could not resolve the package 'gsy_github_app_flutter' in 'package:gsy_github_app_flutter/common/redux/GSYState.dart'.
Error: Could not resolve the package 'gsy_github_app_flutter' in 'package:gsy_github_app_flutter/common/model/User.dart'.

**Comment by CarGuo** [comment]
flutter --version看看， flutter sdk 需要v1.1.3

flutter doctors 看看还有哪些问题。

**Comment by jj89757hhb** [comment]
为啥我执行 flutter --version  无效

**Comment by CarGuo** [comment]
你看看环境命令行的flutter是否已经配置成功
