### ISSUE TITLE
存在已久过时的api

### ISSUE THREAD

**Issue by ai930** [CarGuo/GSYGithubAppFlutter#22]
Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (3 months ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

RawMaterialButton
          materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,  //不存在的

ContentType.TEXT : ContentType.JSON //这里需要改成大写

**Comment by CarGuo** [comment]
嗯，这个知道，一直懒得改回来。😂

**Comment by ai930** [comment]
我需要升级SDK？那我明天升级看看。我是JAVA服务端开发，刚接触这个。你有什么好的学习视频和文章推荐吗？

**Comment by CarGuo** [comment]
你更新下flutter，切换到git 0.5.7的tag就好了。一般官网个人觉得就可以入门了，再稍微理解下dart

**Comment by ai930** [comment]
我升级了SDK 不过出现新问题。有一个依赖过于底。引起错误。dio 需要升级的到1.0.0

**Comment by CarGuo** [comment]
你可以看看，yaml文件和lock文件中的版本是不是对应的上
