### ISSUE TITLE
flutter可以嵌入echarts吗？

### ISSUE THREAD

**Issue by sharpleafage** [CarGuo/GSYGithubAppFlutter#26]
flutter可以嵌入echarts吗？
或者别的图形统计插件

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/6

**Comment by CarGuo** [comment]
https://github.com/thekeenant/fcharts

**Comment by sharpleafage** [comment]
Thanks
