### ISSUE TITLE
从MyPage切换到DynamicPage，会调用MyPage的requestRefresh()。

### ISSUE THREAD

**Issue by GanZhiXiong** [CarGuo/GSYGithubAppFlutter#266]
这个不应该啊，是不是。

**Comment by CarGuo** [comment]
貌似我这边没出现

**Comment by GanZhiXiong** [comment]
@CarGuo  我刚又拉取了你master最新的代码，测试还是复现了。
你可以这么测试，在下图所示位置打断点，然后运行APP，进入动态page后，切换到我的page，等下拉刷新完成后，再切换到动态page，就会调用MyPage的_getDataLogic方法。
正常逻辑不应该这样，这样会导致无用的网络请求，浪费流量，影响性能。
![image](https://user-images.githubusercontent.com/27394631/53487274-19112380-3ac6-11e9-8b22-dfb32acd361b.png)

**Comment by CarGuo** [comment]
https://github.com/flutter/flutter/issues/27680

https://github.com/flutter/flutter/pull/24821


TabBarView 确实存在这个问题，官方目前还未处理好。但是你可以看看项目里的，针对详情页面用的是PageView + Tab 这种配置目前应该是不会导致这个，你可以看看。


同时目前我还不清楚我项目里这个问题是不是也和redux有关系

**Comment by GanZhiXiong** [comment]
好的，thanks！
