### ISSUE TITLE
ios build in adhoc, the app stuck in splash screen

### ISSUE THREAD

**Issue by dev-kang** [CarGuo/GSYGithubAppFlutter#268]
苹果在xcode环境下编译adhoc到测试手机上，启动的时候卡死在闪屏页面上。

**Comment by CarGuo** [comment]
我这边一直正常使用，ios真机上

**Comment by dev-kang** [comment]
这个问题目前我也比较奇怪，archive以后的打包上传到fir.im，然后直接安装，就是卡在闪屏上。。。源码也已经删除过重新下载，重新配置了证书，难倒是证书的问题？

**Comment by CarGuo** [comment]
打开之前要先执行flutter release 生成文件后，再archive

**Comment by dev-kang** [comment]
按照你的方法确实打包成功了，不过我其他的flutter项目并未这样操作，为什么这个项目需要这样操作？

**Comment by CarGuo** [comment]
flutter build ios 会生成对应的release二进制文件，默认打包的debug用的是JIT模式下的二进制文件。

**Comment by dev-kang** [comment]
好的，非常感谢！
