### ISSUE TITLE
底部Tab切换时候趋势的tab会重绘绘制

### ISSUE THREAD

**Issue by superSp** [CarGuo/GSYGithubAppFlutter#271]
首页进去底部三个tab ，选中趋势，往下滑一些，之后在点击tab3 和tab1 最后回到tab2，会发现又会滚动到顶部，应该是重绘了，最近一直在找keep方法。。多tab切换和跳转返回时的保持。。

**Comment by CarGuo** [comment]
是keep住的，应该是出发了新的网络请求导致数据更新了，你可以试试在请求到数据后设置下不再请求看看

**Comment by superSp** [comment]
> 是keep住的，应该是出发了新的网络请求导致数据更新了，你可以试试在请求到数据后设置下不再请求看看

嗯 好的 谢谢啦，用了你的GSYTab控件 但是我跳转的时候回来以后 再点击其他tab就会导致重绘，还有就是3个tab的keep的问题。。我下载了你的代码 ，在好好研究下 ， 谢谢谢

**Comment by CarGuo** [comment]
可以看看这个项目的 GSYTabBarWidget 代码。
主页和仓库详情页都有tab，但是仓库详情页没有这个问题，因为仓库详情页是用 TabBar 和 PageView，而主页是用TabBarView 和 TabBar。你可以对比下看看

**Comment by 312223105** [comment]
Tab中的page加上`with AutomaticKeepAliveClientMixin`，并实现
```
@protected
  bool get wantKeepAlive=>true;
```
即可避免重绘
