### ISSUE TITLE
一直停留在努力加载中

### ISSUE THREAD

**Issue by shizhongyu** [CarGuo/GSYGithubAppFlutter#272]
![image](https://user-images.githubusercontent.com/13025541/52714493-ec90de00-2fd4-11e9-9479-98420f68b383.png)

**Comment by CarGuo** [comment]
自己编译的还是下载的apk

**Comment by shizhongyu** [comment]
自己编译的。

**Comment by CarGuo** [comment]
更新下代码再试试，看看log有没有什么报错

**Comment by shizhongyu** [comment]
[error.txt](https://github.com/CarGuo/GSYGithubAppFlutter/files/2863632/error.txt)
错误log。

**Comment by CarGuo** [comment]
这个log看的有点懵，你本地flutter doctors 看看sdk版本

**Comment by CarGuo** [comment]
我这边测试了1.2.0版本下挺正常的
