### ISSUE TITLE
iOS版本下面，图像无法存储，长按返回按钮的bug

### ISSUE THREAD

**Issue by wwwang89** [CarGuo/GSYGithubAppFlutter#275]
iOS版本下面，1、个人用户的图像点击存储按钮无法存储
2、长按返回按钮 会出现手机震动一下，并弹出“返回” 二字，看截图
![img_0089](https://user-images.githubusercontent.com/3423535/52847320-d0ad4980-3146-11e9-8d1a-d89647dbd347.PNG)

**Comment by CarGuo** [comment]
第一个貌似我记得是因为ios我没做😂，第二个是Flutter自带的。
