### ISSUE TITLE
请教个问题，json.encode的对象比较大时，encode会慢，并且会卡住UI，改如何解决？

### ISSUE THREAD

**Issue by GanZhiXiong** [CarGuo/GSYGithubAppFlutter#285]
![image](https://user-images.githubusercontent.com/27394631/53301642-4b394000-3890-11e9-90df-261103bb98b7.png)

这个问题困扰我一天了，麻烦您解答下，谢谢啦！🙂

**Comment by CarGuo** [comment]
你的问题可以在项目里复现那？一般而言网络端返回的数据也是在Furture内处理完之后在给View层显示。虽然Dart是单线程模式，但是异步能更好的分配调度，貌似我还没遇到你说的。

**Comment by GanZhiXiong** [comment]
可以复现啊。
我写成下面这样也不行
![image](https://user-images.githubusercontent.com/27394631/53317815-21236480-3908-11e9-9f39-f7f4f41d3874.png)
issueHeaderViewModel是一个对象，通过调试发现json.encode比较慢导致UI卡住的，json.encode慢，是因为issueHeaderViewModel这个对象比较大导致的，下面图片是issueHeaderViewModel这个对象
![image](https://user-images.githubusercontent.com/27394631/53317988-aad33200-3908-11e9-83b6-ed860f34907e.png)
json.encode好像不能异步。

**Comment by CarGuo** [comment]
真的数据特别大的话，用 isolate 吧

**Comment by GanZhiXiong** [comment]
@CarGuo   谢谢提示，我用compute解决了，下面是我的代码
![image](https://user-images.githubusercontent.com/27394631/53481654-a2215e00-3ab8-11e9-8a46-b0bae04290f1.png)
但是字符串比较大的话，insert会有一点慢，导致insert的时候卡住UI，下面是你写的insert代码
![image](https://user-images.githubusercontent.com/27394631/53481808-dd239180-3ab8-11e9-8b3d-405b18da8717.png)
我有尝试将`db.insert(name, toMap(fullName, number, dataMapString));`这段代码用compute来调用，试过很多次都失败了，失败原因与db这个对象有关，具体我就不知了。期待你下个版本将数据库操作改为isolate，因为有时候数据量大，比较耗时就会卡住UI

**Comment by CarGuo** [comment]
应该是跨线程了，后续会尝试增加isolate的
