### ISSUE TITLE
Http status error [403]

### ISSUE THREAD

**Issue by hansugus** [CarGuo/GSYGithubAppFlutter#295]
flutter: 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [403]
flutter: 请求异常url: https://api.github.com/users/用户名/received_events?page=1&per_page=20
一半几率成功，一半几率报403

**Comment by CarGuo** [comment]
自己打包的还是下载的…我这边目前测试没遇到过哦

**Comment by hansugus** [comment]
自己打包的，我的是IOS ； 大部分功能正常使用，部分请求403；Github需要特殊设置？

**Comment by CarGuo** [comment]
一般如果你申请了github appid和appsercet正确的，之后用账号密码获取token应该没问题。403 看起来权限问题，你可以看看会不会是和一些用户有关，比如组织或者个人

**Comment by fmricky** [comment]
@CarGuo Github App 的 Permissions 是不是需要什么特殊的设置，开放某些权限？我这边也是大量403.

**Comment by CarGuo** [comment]
哪些地方403？需要的是用用户名登录，不是邮箱哦！然后看看token有没有过期

**Comment by fmricky** [comment]
@CarGuo 
运行时调试信息输出如下，我把403的部分抽出来，可能还有我没有运行到的页面，只是在`趋势`里头运行了一下
> flutter: 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [403]
flutter: 请求异常信息: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/repos/branches/#list-branches"}
flutter: 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [404]
flutter: 请求异常信息: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/activity/starring/#check-if-you-are-starring-a-repository"}
flutter: 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [403]
flutter: 请求异常信息: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/issues/#list-issues-for-a-repository"}
flutter: 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [403]
flutter: 请求异常信息: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/activity/events/#list-events-that-a-user-has-received"}
flutter: 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [403]
flutter: 请求异常信息: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/activity/events/#list-public-events-for-a-network-of-repositories"}
flutter: 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [403]
flutter: 请求异常信息: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/repos/contents/#get-the-readme"}

**Comment by CarGuo** [comment]
趋势的数据是爬网页哦，并没有通过接口请求
