### ISSUE TITLE
flutter 序列化

### ISSUE THREAD

**Issue by smarthityou** [CarGuo/GSYGithubAppFlutter#298]
麻烦大神，flutter在序列化的时候是否可以支持通用类型数据 如：接口返回的数据{State: 200, Error: , Result: 泛型T}，我搜索了下 貌似flutter不支持反射

**Comment by CarGuo** [comment]
一般我都是

static List<dynamic> decodeListResult(String data) {
    return json.decode(data);
  }

  static Map<String, dynamic> decodeMapResult(String data) {
    return json.decode(data);
  }

泛型你可以需要参考 https://yq.aliyun.com/articles/689249?spm=a2c4e.11153959.teamhomeleft.51.7eab2529HkOHBf
