### ISSUE TITLE
运行flutter packages get出现异常

### ISSUE THREAD

**Issue by GanZhiXiong** [CarGuo/GSYGithubAppFlutter#299]
Running "flutter packages get" in GSYGithubAppFlutter-master...     
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because no versions of build_runner match >1.2.8 <2.0.0 and build_runner 1.2.8 depends on build_daemon ^0.4.0, build_runner ^1.2.8 requires build_daemon ^0.4.0.
So, because build_daemon >=0.2.0 requires SDK version >=2.1.0 <3.0.0 and gsy_github_app_flutter depends on build_runner ^1.2.8, version solving failed.

pub get failed (1)
Process finished with exit code 1

对应图片如下：
![image](https://user-images.githubusercontent.com/27394631/53783465-9ae0d100-3f4c-11e9-97fb-d3a3c0ecb17c.png)

我有如下问题请教：
1、出现这个错误是不是需要更新flutter？
2、著者用的flutter分支是不是stable分支？（只是flutter中文网的介绍：我们强烈建议跟踪flutter的stable分支，这是Flutter稳定分支。 如果你需要查看最新的变化，你可以跟踪master分支，但注意这是开发分支，所以稳定性要低得多。）

**Comment by CarGuo** [comment]
你可以看github readme，每次跟进我都会把sdk版本写到github readme上。

**Comment by GanZhiXiong** [comment]
好的。大佬知道这个问题怎么解决吗？
https://github.com/CarGuo/TabBarWithPageView/issues/1#issuecomment-469307923

**Comment by CarGuo** [comment]
这个你目前还没去弄过，不过你可以看看flutter的碰撞测试机制hintTest和冒泡
