### ISSUE TITLE
Because no versions of build_runner match >1.2.8 <2.0.0 and build_runner 1.2.8 depends on build_daemon ^0.4.0, build_runner ^1.2.8 requires build_daemon ^0.4.0. So, because build_daemon >=0.2.0 requires SDK version >=2.1.0 <3.0.0 and gsy_github_app_flutter depends on build_runner ^1.2.8, version solving failed.

### ISSUE THREAD

**Issue by Everglowzz** [CarGuo/GSYGithubAppFlutter#300]
clone下来运行报如下错误：
Because no versions of build_runner match >1.2.8 <2.0.0 and build_runner 1.2.8 depends on build_daemon ^0.4.0, build_runner ^1.2.8 requires build_daemon ^0.4.0.
So, because build_daemon >=0.2.0 requires SDK version >=2.1.0 <3.0.0 and gsy_github_app_flutter depends on build_runner ^1.2.8, version solving failed.
我应该怎么修改配置呢？

**Comment by Everglowzz** [comment]
哦，我提重复问题了，关掉吧

**Comment by manburenshenglu** [comment]
怎么解决的呢？我已经切换到redme上说的Flutter SDK 版本 v1.3.2 啦，求解
