### ISSUE TITLE
mate 20 无法打开键盘

### ISSUE THREAD

**Issue by DaemonSu** [CarGuo/GSYGithubAppFlutter#306]
在mate 20上，登录界面用户名文本框获得焦点好后无法显示键盘，控制台显示：
I/InputMethodManager(25660): showSoftInput
I/InputMethodManager(25660): mServedView =com.shuyu.gsygithub.gsygithubappflutter;view =com.shuyu.gsygithub.gsygithubappflutter;flags =0
W/InputMethodManager(25660): The current service view is not the focus view

但是如果下载发布版本，则可以打开键盘。
大神帮忙分析下是什么问题。

**Comment by DaemonSu** [comment]
在荣耀8 上使用没有问题，mate 20上有问题，把安全键盘关闭了也不可以。

**Comment by CarGuo** [comment]
至少1.2以上

**Comment by DaemonSu** [comment]
不是flutter版本问题。
把android 下的build.gradle 文件中的compileSdkVersion  从28改成27 targetSdkVersion 也从28改成27就好了。谢谢作者！

**Comment by CarGuo** [comment]
新版本28下已经修复了这个问题了
