### ISSUE TITLE
我的项目和你之前回答的这个问题一样，在ios上也是出现了这样的问题？

### ISSUE THREAD

**Issue by gaojuanjuan** [CarGuo/GSYGithubAppFlutter#308]
https://github.com/flutter/flutter/issues/19120#issuecomment-464278572

**Comment by CarGuo** [comment]
编译失败请看readme，你需要自己加上ignoreconfig文件，readme上写着

**Comment by CarGuo** [comment]
不好意思关错了，这个问题我这边现在没出现了，正常状态····
