### ISSUE TITLE
在小米6/Android 8.0上的性能问题？

### ISSUE THREAD

**Issue by ArchangelXu** [CarGuo/GSYGithubAppFlutter#315]
[device-2019-02-27-141221.mp4.zip](https://github.com/CarGuo/GSYGithubAppFlutter/files/2908796/device-2019-02-27-141221.mp4.zip)

确实是比RN版本要卡顿一些，RN版本和原生体验基本一致，Flutter会有点卡，尤其是在左右切换Tab的时候

_Originally posted by @ArchangelXu in https://github.com/CarGuo/GSYGithubAppFlutter/issues/45#issuecomment-467737300_

**Comment by CarGuo** [comment]
说实话，我没感觉到卡····那个左右切换的时候的那个最后缓入，应该是pageview 的ScrollSpringSimulation
