### ISSUE TITLE
something wrong when debug in vs code

### ISSUE THREAD

**Issue by MyateJx** [CarGuo/GSYGithubAppFlutter#32]
Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  D:\Projects\flutterDemos\GSYGithubAppFlutter\lib\common\dao\UserDao.dart
...refers, in an import, to the following library:
  D:\Projects\flutterDemos\GSYGithubAppFlutter\lib\common\config\ignoreConfig.dart
Unfortunately, that library does not appear to exist on your file system.

**Comment by CarGuo** [comment]
it had ignore, you need create ignoreConfig.dart in `lib/common/config/` ，and input your Github client_id andclient_secret，which your register from githubApp ：  https://github.com/settings/applications/new

**Comment by MyateJx** [comment]
@CarGuo it is a pity that i'm new comer and can not solve it, it seems that some dependencies were outdated ...

![image](https://upload-images.jianshu.io/upload_images/57036-c4ac9783728a9b2c.png)

**Comment by CarGuo** [comment]
you must register from github  https://github.com/settings/applications/new


[ignoreConfig.dart.zip](https://github.com/CarGuo/GSYGithubAppFlutter/files/2302420/ignoreConfig.dart.zip)

take your Github client_id andclient_secret，then put the ignoreConfig.dart to dirs like below ：

<img width="335" alt="2018-08-20 8 52 55" src="https://user-images.githubusercontent.com/10770362/44341723-5794a880-a4bb-11e8-92e1-4b3160639dc7.png">

**Comment by MyateJx** [comment]
@CarGuo excuse me ???
不不不，大兄弟，请问这么做的依据是。。
依赖项的过期，与ignoreConfig有必然的联系？目前遭遇的问题是项目api过期，IDE报红不让编译。

**Comment by CarGuo** [comment]
![5b7b72e0e4b0e7b6f15f731b](https://user-images.githubusercontent.com/10770362/44376060-569a6000-a529-11e8-8c0c-69326a04208e.jpg)


you must confirm `ignoreConfig.dart`  is exist. 
local flutter sdk version local is v0.5.8.

**Comment by MyateJx** [comment]
@CarGuo thanks anyway, i'll try.
