### ISSUE TITLE
The getter 'currentLocalized' was called on null.

### ISSUE THREAD

**Issue by LiJian0129** [CarGuo/GSYGithubAppFlutter#321]
使用BottomNavigationBarItem 时，切换的page用getLocale是就出现这个错误，求大神告知

**Comment by CarGuo** [comment]
当前项目有这个问题？

**Comment by LiJian0129** [comment]
你的项目没有改问题

**Comment by CarGuo** [comment]
我觉得是context在往上找的时候找不到Locale

**Comment by LiJian0129** [comment]
的确是这样。。具体是啥问题，是redux配置不对吗？

**Comment by LiJian0129** [comment]
我在前面注册主页都没问题，，就是在主页内的切换的tab页出现问题。。我通过Localizations.of（context）获取的确实en的。头大

**Comment by liupeng826** [comment]
找到原因了？我也出现这个问题了
