### ISSUE TITLE
如果添加webview_flutter这个包运行会出现异常

### ISSUE THREAD

**Issue by GanZhiXiong** [CarGuo/GSYGithubAppFlutter#323]
异常为：
[VERBOSE-3:FlutterPlatformViews.mm(152)] Check failed: factories_.count(idString) == 0.

**Comment by CarGuo** [comment]
webview_flutter 已经源码内置了

**Comment by GanZhiXiong** [comment]
我将最新的webview_flutter: ^0.3.5+2源码内置，可以打开网页，但是无法使用它更新的回调，如navigationDelegate、onPageFinished，虽然不会报错，但是回调不会执行。我新建一个项目通过在pubspec.yaml文件中声明，同样的代码这些回调是可以调用的

**Comment by GanZhiXiong** [comment]
![image](https://user-images.githubusercontent.com/27394631/54874249-3cf42a80-4e22-11e9-8dd5-be6de49308f7.png)
这些回调都不会执行，是不是只源码内置是不够的呀

**Comment by GanZhiXiong** [comment]
我觉得还是得从pub引入webview_flutter这个包出现如下异常入手
[VERBOSE-3:FlutterPlatformViews.mm(152)] Check failed: factories_.count(idString) == 0.

**Comment by GanZhiXiong** [comment]
通过xcode调试我已经解决了这个问题，调试发现是如下图所示的注释的代码导致的报错，于是我将其注释，运行通过，onPageFinished也能回调了。

**如下图红框中的四个文件我也不知道是怎么来的，正常pub中声明这个包，是不会出现这四个文件的。**

![image](https://user-images.githubusercontent.com/27394631/54877099-01bf1f00-4e55-11e9-90d5-b4a45808a2c5.png)
