### ISSUE TITLE
你好，我觉得你的flutter项目很好，我有企业签名 可以免费帮忙签 也算为开源做一点贡献，请问还需要吗

### ISSUE THREAD

**Issue by NickTet** [CarGuo/GSYGithubAppFlutter#326]
你好，我觉得你的flutter项目很好，我有企业签名 可以免费帮忙签 也算为开源做一点贡献，请问还需要吗

**Comment by CarGuo** [comment]
可以的～～哈哈哈，请问下你这边帮忙怎么签发的？或者你可以直接打包签好发给我，我更新上去，或者直接发个链接也行～目前可以打 1.2.0  这个tag的～～

**Comment by NickTet** [comment]
没续费  gg了
