### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by angBiu** [CarGuo/GSYGithubAppFlutter#329]
fatal error: 'connectivity/ConnectivityPlugin.h' file not found
    #import <connectivity/ConnectivityPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated

搞不懂为啥找不到呢。。Xcode打开文件存在就是引用不了

**Comment by CarGuo** [comment]
你这是没有安装插件吧，然后在看看你本地flutter sdk版本

**Comment by angBiu** [comment]
插件安装了。。用Xcode打开也是报错。。flutter 1.2.1，感觉不是flutter版本问题，找找看看了。。

**Comment by angBiu** [comment]
因为公司原因pod设定为1.2.1，升级到最新的cocoapods版本可以了 3Q

**Comment by CarGuo** [comment]
good
