### ISSUE TITLE
真的比RN版卡很多，没有对比就没有伤害。

### ISSUE THREAD

**Issue by ArchangelXu** [CarGuo/GSYGithubAppFlutter#330]
录的视频确实没有在手机上那么明显。所以我又录了一个，可以对比一下，前半段是Flutter，后半段是RN，这个流畅度的差异就很明显了
[device-2019-03-27-150505.mp4.zip](https://github.com/CarGuo/GSYGithubAppFlutter/files/3011932/device-2019-03-27-150505.mp4.zip)

**Comment by CarGuo** [comment]
你不能对比debug模式的，flutter 的debug和release是 JIT 和 AOT 的区别，对比release 才是

**Comment by ArchangelXu** [comment]
> 你不能对比debug模式的，flutter 的debug和release是 JIT 和 AOT 的区别，基本上是两种流畅状态，对比release 才是
好吧。我又从主页上提供的蒲公英链接下载测试了一下：
[device-2019-03-27-160055.mp4.zip](https://github.com/CarGuo/GSYGithubAppFlutter/files/3012108/device-2019-03-27-160055.mp4.zip)

**Comment by CarGuo** [comment]
如果是你对滑动速度和阻尼效果的疑问的话，因为flutter是有各种滑动效果和阻尼效果的，还有划一下多远等方法的，你可以了解下。

**Comment by ArchangelXu** [comment]
> 如果是你对滑动速度和阻尼效果的疑问的话，因为flutter是有各种滑动效果和阻尼效果的，还有划一下多远等方法的，你可以了解下。

好吧。
