### ISSUE TITLE
epic作用？

### ISSUE THREAD

**Issue by fdtl01** [CarGuo/GSYGithubAppFlutter#343]
![image](https://user-images.githubusercontent.com/36351484/55624085-7429ea80-57d7-11e9-8cdc-808b54bc43c9.png)
如上图，这部分代码出自哪里，主要是做什么的，看到flutter_redux，然后看到用到epic，主要是干啥的？

**Comment by CarGuo** [comment]
这是中间件，做中间异步处理的
