### ISSUE TITLE
term_glyph.dart ? petitparser.dart? http_parser.dart?

### ISSUE THREAD

**Issue by lionnner** [CarGuo/GSYGithubAppFlutter#348]
已经设置好的前提下会报缺少这三个依赖。
添加进后 就可以正常运行了。

**Comment by CarGuo** [comment]
这几个是flutter自己依赖带着的，比如

term_glyph.dart ：

https://github.com/flutter/flutter/blob/2736c8c19f636fe74d600ae2b7ec2e777cb917f2/packages/flutter/pubspec.yaml#L42

http_parser.dart：

https://github.com/flutter/flutter/blob/1bfa2f23114829513a9d2c0a7a27d743287acc2a/dev/tools/pubspec.yaml#L23
