### ISSUE TITLE
断网重连后下拉刷新失效

### ISSUE THREAD

**Issue by fg2q1q3q** [CarGuo/GSYGithubAppFlutter#353]
感谢开源，使用过程发现一个问题：断开网络进入首页提示网络错误，然后连接网络下拉刷新会失效

**Comment by CarGuo** [comment]
收到～

**Comment by CarGuo** [comment]
是这样的场景吗？我测试了是，进去的时候断网，然后提示失败，然后打开网络，然后在刷新？

这个场景目前就最新代码没有问题了

**Comment by fg2q1q3q** [comment]
哦，那有可能，我是两星期前clone的代码
