### ISSUE TITLE
自定义弹框能滑动

### ISSUE THREAD

**Issue by GiveSmile** [CarGuo/GSYGithubAppFlutter#362]
在点击回复按钮出现的弹出框 在输入法出来的时候 弹出框能滑动到顶部以上
![图片](https://user-images.githubusercontent.com/45993544/56562415-dd816a00-65db-11e9-9858-7f60bcdf43b8.png)

**Comment by GiveSmile** [comment]
在点击回复按钮出现的弹出框  在输入法出来的时候 弹出框能滑动到顶部以上

**Comment by CarGuo** [comment]
是的，故意的
