### ISSUE TITLE
在登录页面，我得输入法弹出和取消都会触发登录的路由页面，这样是正常的吗？

### ISSUE THREAD

**Issue by joucksHua** [CarGuo/GSYGithubAppFlutter#369]
在登录页面，我得输入法弹出和取消都会触发登录的路由页面，这样是正常的吗？
![image](https://user-images.githubusercontent.com/24910959/56860279-75f66080-69c7-11e9-95df-4dcf0e07ec18.png)
就是这里，main里的登录路由

**Comment by CarGuo** [comment]
不走 build 你的页面怎么可能发生变化呢，要知道每个画面都是一帧
