### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by haitianZhu** [CarGuo/GSYGithubAppFlutter#37]
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because flutter_markdown 0.1.6 requires SDK version >=1.19.0 <2.0.0 and no versions of flutter_markdown match >0.1.6 <0.2.0, flutter_markdown ^0.1.6 is forbidden.
So, because gsy_github_app_flutter depends on flutter_markdown ^0.1.6, version solving failed.
pub get failed (1)

切换flutter master后，flutter_markdown、json_serializable都会报错

**Comment by haitianZhu** [comment]
最新的beta是0.5.1，好多属性没有

**Comment by CarGuo** [comment]
库使用的是0.5.7，你需要切换到Flutter 的 v0.5.7的tag
