### ISSUE TITLE
求教一下

### ISSUE THREAD

**Issue by Anzhi-Meiying** [CarGuo/GSYGithubAppFlutter#386]
Flutter中怎么对apk进行安全保护，比如原生中的获取apk签名验证在Flutter中有API可供进行吗

**Comment by CarGuo** [comment]
你是说 getPackageInfo ？这个在Flutter中官方有支持的。
package_info 的包中有

PackageInfo packageInfo = await PackageInfo.fromPlatform();

**Comment by Anzhi-Meiying** [comment]
好的谢谢，ZipEntry这个呢

**Comment by CarGuo** [comment]
如果你说zip解压或者的是获取crc32的话，我记得好像有类似的 crclib ，archive 之类的库，

**Comment by Anzhi-Meiying** [comment]
非常感谢
