### ISSUE TITLE
编译报错，请问这个怎么解决？

### ISSUE THREAD

**Issue by 542604974** [CarGuo/GSYGithubAppFlutter#388]
file:///Users/mdmac01/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.12.4/lib/src/utilities/errors.dart:10:29: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/mdmac01/Desktop/FlutterSDK/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
      informationCollector: (StringBuffer buff) {
                            ^
Compiler failed on /Users/mdmac01/Downloads/GSYGithubAppFlutter-master/lib/main.dart
Error launching application on iPhone Xs.

**Comment by CarGuo** [comment]
你确定下你的本地 Flutter 版本

**Comment by 542604974** [comment]
1.5.9-pre.150  这个版本

**Comment by CarGuo** [comment]
试试 1.5.8

**Comment by 542604974** [comment]
好的，谢谢！
