### ISSUE TITLE
提一个建议

### ISSUE THREAD

**Issue by kadoyatsukasa** [CarGuo/GSYGithubAppFlutter#400]
也许可能有点难度，大佬，有没有想过把系列文章做成一本gitbook，或者类似的文稿？或者做一本掘金小册？现在你的文章分散在那里，看起来有点麻烦😁😁😁只是个可能会强人所难的建议，也可以选择无视😁😁😁

**Comment by CarGuo** [comment]
有在打算整理成小册的打算，等这个月线下沙龙之后吧。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYFlutterBook
