### ISSUE TITLE
学习疑问

### ISSUE THREAD

**Issue by kadoyatsukasa** [CarGuo/GSYGithubAppFlutter#402]
在[gsy_tabbar_widget](https://github.com/CarGuo/GSYGithubAppFlutter/blob/master/lib/widget/gsy_tabbar_widget.dart)里面有个地方不太明白
```
_onPageChanged?.call(index);
```
这里这个call()方法的定义怎么找不到？no definition found for 'call'

**Comment by CarGuo** [comment]
Dart 为了能够让类可以像像函数一样调用，默认都可以实现 call() 方法，而 typedef 定义的方法也是具备 call() ；


比如我修改了

```
class TarWidgetControl {
  List<Widget> footerButton = [];

  call(int i, double e) => "$i xxxx $e";
}

```

就可以通过以下执行

```
print(widget.tarWidgetControl(11, 11.0));
```

然后我定义了 
```
typedef void ValueII(int i);

  ValueII tt = (int i){
    print("zzz $i");
  };

```
就可以通过直接执行和判空执行处理

```
 tt(666);
 tt?.call(777);

```

**Comment by kadoyatsukasa** [comment]
也就是说```tt?.call(777)```等价于```tt(777)```，```_onPageChanged?.call(index);```等价于```_onPageChanged(index)```的意思？？？

**Comment by CarGuo** [comment]
是的，只是增加了 ? 进行判空 。 比如 tt 为 null 的时候，不会执行

**Comment by kadoyatsukasa** [comment]
你的[middleware](https://github.com/CarGuo/GSYGithubAppFlutter/tree/master/lib/common/redux/middleware)是你自己写的，还是从哪个第三方库下载过来的？都是英文，有点难啃

**Comment by CarGuo** [comment]
https://github.com/brianegan/dart_redux_epics  之前不支持dart2，所以源码引入

**Comment by kadoyatsukasa** [comment]
那可不可以改成包引入的形式？现在可以直接import这个包了。如果不方便的话，我可以来操作么？https://pub.dev/packages/redux_epics

**Comment by kadoyatsukasa** [comment]
大佬，如何对一个完整项目进行整体规划？我这第一次自己进行项目，没有一个整体规划，写下来之后，整个就是很乱

**Comment by CarGuo** [comment]
em·····这个，要不你找本软件工程看看
