### ISSUE TITLE
network_cache_image.dart 中报错

### ISSUE THREAD

**Issue by SuperCup** [CarGuo/GSYGithubAppFlutter#407]
> ImageStreamCompleter load(NetworkCacheImage key) {
    return MultiFrameImageStreamCompleter(
      codec: _loadAsync(key),
      scale: key.scale,
      informationCollector: (StringBuffer information) {
        information.writeln('Image provider: $this');
        information.write('Image key: $key');
      },
    );
  }
报错如下：
The argument type '(StringBuffer) → Null' can't be assigned to the parameter type '() → Iterable<DiagnosticsNode>'.dart(argument_type_not_assignable)

**Comment by CarGuo** [comment]
更新代码，更新到readme中的sdk版本
