### ISSUE TITLE
clone下来项目执行get dependences报错：Git error. Command: git fetch

### ISSUE THREAD

**Issue by manburenshenglu** [CarGuo/GSYGithubAppFlutter#414]
![image](https://user-images.githubusercontent.com/13146756/58445287-aea46980-812e-11e9-89b5-e1a9d128d6d0.png)

**Comment by CarGuo** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/10770362/58446116-0db7ad80-8132-11e9-9a20-bd1caa7d8b9a.png">

这两个git项目应该存在的

**Comment by manburenshenglu** [comment]
![image](https://user-images.githubusercontent.com/13146756/58446904-1b226700-8135-11e9-8dad-51cbd838cdbd.png)
这两个git项目有，但是报git fetch 错误

**Comment by CarGuo** [comment]
我刚刚到另外一台电脑试了，正常

**Comment by CarGuo** [comment]
请重新拉取代码后更新 ，问题解决请参考 https://github.com/CarGuo/GSYGithubAppFlutter/issues/415

**Comment by manburenshenglu** [comment]
好的谢谢，我试一下
