### ISSUE TITLE
package get报错

### ISSUE THREAD

**Issue by kadoyatsukasa** [CarGuo/GSYGithubAppFlutter#415]
下拉了一下更新，然后，packages get获取一下包，出现以下报错
```
[GSYGithubAppFlutter] flutter packages get
Running "flutter packages get" in GSYGithubAppFlutter...        
Could not find a file named "pubspec.yaml" in https://github.com/CarSmallGuo/photo_view.git 1fc0effdb8269f4f6bb61186acb127890002b770.
pub get failed (1)
exit code 1
```

**Comment by CarGuo** [comment]
你再更新下代码，然后再拉看看

**Comment by CarGuo** [comment]
还有问题没？

**Comment by CarGuo** [comment]
找到问题了，比如 

win  是在 `C:\Users\xxxxx\AppData\Roaming\Pub\Cache`  路径下有 git 目录，如果存在某次 package get 失败之后，git 下目录会存在，然后出现这个异常。 可以删除 git 目录有重新packages get


mac 目录在 `~/.pub-cache`

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/415
