### ISSUE TITLE
package get报错

### ISSUE THREAD

**Issue by RABBITGUO** [CarGuo/GSYGithubAppFlutter#419]
Could not find a file named "pubspec.yaml" in https://github.com/CarSmallGuo/photo_view.git 6be6a50adfcead0e727a982d32090b9efec9e896.
pub get failed (1)

**Comment by CarGuo** [comment]
你试试本地git clone能不能clone下来

**Comment by CarGuo** [comment]
找到问题了，比如 

win  是在 `C:\Users\xxxxx\AppData\Roaming\Pub\Cache`  路径下有 git 目录，如果存在某次 package get 失败之后，git 下目录会存在，然后出现这个异常。 可以删除 git 目录有重新packages get


mac 目录在 `~/.pub-cache`

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/415
