### ISSUE TITLE
下载你的app，运行登录的时候，报错返回422！

### ISSUE THREAD

**Issue by ZLdeSpirit** [CarGuo/GSYGithubAppFlutter#424]

**Comment by CarGuo** [comment]
登陆失败？？请用 github 账号名登陆，比如账号  ZLdeSpirit ，密码 xxxxx，请勿用邮箱

https://github.com/CarGuo/GSYGithubAppFlutter/issues/13

**Comment by ZLdeSpirit** [comment]
是的，我确实使用的账号登录的，并非使用邮箱登录，之前使用你的app登录成功了的，之后使用就失败了！谢谢

**Comment by ZLdeSpirit** [comment]
返回信息：
请求url：https://api.github.com/authorizations
I/flutter (32221): 请求头: {Authorization: Basic WkxkZVNwaXJpdDppY2UuemwxMTAuQC4uQA==}
I/flutter (32221): 请求参数: {"scopes":["user","repo","gist","notifications"],"note":"admin_script"}
I/flutter (32221): 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [422]
I/flutter (32221): 请求异常信息: {"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"note"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}

**Comment by CarGuo** [comment]
账号没有开启两步认证吧？没有的话应该没问题啊，这么奇怪···有试过其他账号吗？

**Comment by ZLdeSpirit** [comment]
没有试过其它账号，我只有这一个账号，我再看看吧！

**Comment by CarGuo** [comment]
这么奇怪，我刚刚试了登陆了几次都听正常的，对了，如果没有 开启两步认证 的话，你先试试手机上打开github登陆网页能不能正常，有时候也有dns导致的问题之类的。

**Comment by ZLdeSpirit** [comment]
好的，我先试试登录网页是否正常，对了，您能说说两步认证嘛？

**Comment by CarGuo** [comment]
就是github 通过手机号做验证码之后才能登陆，因为之前我测试的时候没有中国的区号，加不了验证码·····

**Comment by CarGuo** [comment]
我刚刚更新了 apk ，1.5.0的版本，你也重新下载个看看

**Comment by ZLdeSpirit** [comment]
好的，我先试试，我刚刚使用浏览器登录是能够正常登录的！
