### ISSUE TITLE
表哥帮个忙

### ISSUE THREAD

**Issue by YinRenjie1993** [CarGuo/GSYGithubAppFlutter#43]
![image](https://user-images.githubusercontent.com/11569655/44731877-bb038380-ab16-11e8-8859-827867796db7.png)
知道dart下怎么转换时区吗，差了8个小时

**Comment by CarGuo** [comment]
表哥 = =？

哈哈哈，如下图，看起来正常啊

![5b8600a2e4b0eb3cfd6b59cf](https://user-images.githubusercontent.com/10770362/44760963-d8b30600-ab73-11e8-905e-5c681e0350db.jpg)
