### ISSUE TITLE
关于类似微信或者支付宝收款的语音播报功能如何实现

### ISSUE THREAD

**Issue by weiyunpeng** [CarGuo/GSYGithubAppFlutter#431]
关于类似微信或者支付宝收款的语音播报功能如何实现

**Comment by CarGuo** [comment]
这个直接接入原生插件，同构 MethodChannel 调用就可以了

**Comment by weiyunpeng** [comment]
> 这个直接接入原生插件，同构 MethodChannel 调用就可以了

能不能说的再雪薇详细点，或者有demo链接看看
