### ISSUE TITLE
请问图标库wxcIconFont的图标列表哪里可以查看？

### ISSUE THREAD

**Issue by CCY0122** [CarGuo/GSYGithubAppFlutter#432]
请问图标库wxcIconFont列表哪里可以看呢？
我看代码中是直接填codePoint：
IconData(0xe684, fontFamily: "wxcIconFont")。请问哪里可以看codePoint对应的具体图标UI？

**Comment by CarGuo** [comment]
wxcIconFont这个字体库是我自己添加的啊……这是一个字体文件
