### ISSUE TITLE
photo_view compiler

### ISSUE THREAD

**Issue by GanZhiXiong** [CarGuo/GSYGithubAppFlutter#435]
![image](https://user-images.githubusercontent.com/27394631/58869381-b0eb6280-86f0-11e9-877c-afd18a224a24.png)

估计是你GitHub的photo_view和pub上的photo_view有冲突，我有使用过photo_view，本地有缓存，估计你的photo_view得换个名字

**Comment by CarGuo** [comment]
不是，我修改过的 photo_view 是引用 git 的，在 pub_cache 里是会有 hash 值的，你这是本地sdk太低了我估计，本地sdk需要 1.6以上

**Comment by GanZhiXiong** [comment]
![image](https://user-images.githubusercontent.com/27394631/58872310-4e956080-86f6-11e9-9918-512fd304ea19.png)
你用的是那个分支呀，我用的是stable，没有最新的版本啊。
![image](https://user-images.githubusercontent.com/27394631/58872376-72f13d00-86f6-11e9-851f-648c719120ad.png)

**Comment by CarGuo** [comment]
是的，我一直总得beta版本，因为stable更新太慢了，问题修复不及时

**Comment by GanZhiXiong** [comment]
我升级到了beta最新版本，但是还是报错了

![image](https://user-images.githubusercontent.com/27394631/58876034-8d7be400-86ff-11e9-945e-80865901293b.png)

![image](https://user-images.githubusercontent.com/27394631/58876116-bb612880-86ff-11e9-980a-eb88789236e1.png)

**Comment by CarGuo** [comment]
更新下代码后重新packages get 这个仓库我今天更新过了，因为这个仓库对新版本没处理

**Comment by GanZhiXiong** [comment]
嗯，问题解决了，Android和iOS都能编译成功👍👍👍
Thanks.
