### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by tg-admin** [CarGuo/GSYGithubAppFlutter#442]
![image](https://user-images.githubusercontent.com/35056021/59171538-e91df580-8b75-11e9-821c-ecf60b35910c.png)

环境已经改变

![image](https://user-images.githubusercontent.com/35056021/59171571-15397680-8b76-11e9-881a-348978a9b7ed.png)

**Comment by CarGuo** [comment]
看起来是gradle版本没同步到
