### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by mehao** [CarGuo/GSYGithubAppFlutter#45]
是flutter的性能问题还是我手机性能不行，还是说你写的写法有问题呢？在列表下滑动，比起原生的列表卡太多了，严重失帧，不流畅。。。

**Comment by CarGuo** [comment]
直接下的apk么？我这边听正常的

**Comment by mehao** [comment]
clone 代码编译和下载apk都会，手机是小米mix 1

**Comment by CarGuo** [comment]
方便上传个录屏看看么？我这边红米5plus和华为都挺正常的，模拟器也正常。或者你可以试试其他机器？

**Comment by mehao** [comment]
录屏之后就感觉不出卡屏了，但是实际滑动的话就会一顿一顿的

**Comment by CarGuo** [comment]
刚刚在我的Q群里让大家测试了下，红米1s都可以正常使用

**Comment by mehao** [comment]
换了一部手机，三星S8，还是会有卡顿的现象，体验没有原生的好

**Comment by MichaelArchangel** [comment]
[device-2019-02-27-140900.mp4.zip](https://github.com/CarGuo/GSYGithubAppFlutter/files/2908786/device-2019-02-27-140900.mp4.zip)
确实是比RN版本要卡顿一些，RN版本和原生体验基本一致，Flutter会有点卡，尤其是在左右切换Tab的时候
