### ISSUE TITLE
APK运行一直卡在动画界面

### ISSUE THREAD

**Issue by android-zj** [CarGuo/GSYGithubAppFlutter#451]
APK运行一直卡在动画界面,这是什么原因了 大佬.

**Comment by CarGuo** [comment]
下载的apk？

**Comment by android-zj** [comment]
对，普通下载或二维码下载都是------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>
发送时间: 2019年6月13日(星期四) 下午5:44
收件人: "CarGuo/GSYGithubAppFlutter"<GSYGithubAppFlutter@noreply.github.com>;
抄送: "android-zj"<646909157@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CarGuo/GSYGithubAppFlutter] APK运行一直卡在动画界面 (#451)



下载的apk？
 
&mdash;

**Comment by CarGuo** [comment]
@android-zj 奇怪，我这边挺正常的

**Comment by CarGuo** [comment]
好想还真我的问题导致的

**Comment by CarGuo** [comment]
可以了，重新下载吧，我之前上传的apk只签到了我自己手机····失误失误
