### ISSUE TITLE
flutter packages get

### ISSUE THREAD

**Issue by android-zj** [CarGuo/GSYGithubAppFlutter#452]
Running "flutter pub get" in GSYGithubAppFlutter-master...
Could not find a file named "flare_dart/pubspec.yaml" in git://github.com/2d-inc/Flare-Flutter.git 396cd88df763
8b86e55b4467364fa2c41cde1558.
pub get failed (1)
大佬get packages很多次都包这个错,https://github.com/2d-inc/Flare-Flutter.git 这上面也找不到flare_dart

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/13#issuecomment-496960086

flare_dart 比较大，如果中途失败确实会有问题，重新拉下代码
