### ISSUE TITLE
请教混合开发

### ISSUE THREAD

**Issue by mcxinyu** [CarGuo/GSYGithubAppFlutter#456]
请问有没有混合开发的例子呢？

另外，https://guoshuyu.cn/home/wx/Flutter-1.html
这个教程中“5、Flutter 页面”完成的列表是不是很卡呢？

**Comment by CarGuo** [comment]
？？

**Comment by mcxinyu** [comment]
我是想问android 原生项目和 flutter混合的内容；

**Comment by CarGuo** [comment]
https://github.com/alibaba/flutter_boost
