### ISSUE TITLE
 More than one file was found with OS independent path 'lib/x86/libflutter.so'

### ISSUE THREAD

**Issue by petma** [CarGuo/GSYGithubAppFlutter#460]
More than one file was found with OS independent path 'lib/x86/libflutter.so'

用的最新的

**Comment by CarGuo** [comment]
？？？没发现这个问题啊

**Comment by petma** [comment]
应该是我环境的问题，跑的时候提示我版本低了，升级后就成这样了，所有项目都这样了

**Comment by CarGuo** [comment]
我目前 beta 版最新正常，你试试重装下环境呗

**Comment by petma** [comment]
切换分支"master" to "stable" 问题解决
