### ISSUE TITLE
现在flutter版本没有readme中的版本其他版本编译失败，望解决

### ISSUE THREAD

**Issue by sc956156617** [CarGuo/GSYGithubAppFlutter#463]
Compiler message:
file:///~/.pub-cache/git/photo_view-966b32661fbb6a2170871d80edb07e418c392e36/lib/photo_view.dart:382:5: Error: 'ImageStreamListener' isn't a type.
    ImageStreamListener listener = new ImageStreamListener(listenerSuccess);

**Comment by sc956156617** [comment]
flutter 1.6.1版本

**Comment by CarGuo** [comment]
这个问题已经解决过了

**Comment by sc956156617** [comment]
i got the message,when `flutter run` with v1.6.1  just now.
```
Compiler message:
file:///~/.pub-cache/git/photo_view-966b32661fbb6a2170871d80edb07e418c392e36/lib/photo_view.dart:382:5: Error: 'ImageStreamListener' isn't a type.
ImageStreamListener listener = new ImageStreamListener(listenerSuccess);
```
where i can find the way to work out. please tell me .

**Comment by CarGuo** [comment]
sorry ,  please update to v1.6.3 with beta branch

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/10770362/59812948-58e46b00-9342-11e9-951b-e4ef363add6a.png">

**Comment by sc956156617** [comment]
thank you very much
