### ISSUE TITLE
开发环境

### ISSUE THREAD

**Issue by zhangrurong8** [CarGuo/GSYGithubAppFlutter#466]
flutter_windows_v1.5.4-hotfix.2-stable  请问在这个环境下怎么运行项目啊，因为我想在stable分支下运行。

**Comment by CarGuo** [comment]
这个项目还不支持win版本啊？？？

**Comment by zhangrurong8** [comment]
登录报 其他异常 Invalid argument,请问是什么问题啊？

**Comment by CarGuo** [comment]
配置了正确的 github appid 和 appsercet 吗，然后用用户名密码登陆，不要用邮箱

**Comment by zhangrurong8** [comment]
配置了class NetConfig {
  static const CLIENT_ID = "9db7d904c831703171da";
  static const CLIENT_SECRET = "8ce04e0876300ef8d769a2bbb9c7b05a887f7d23";
}

**Comment by CarGuo** [comment]
如果配置正确，那应该没问题

**Comment by zhangrurong8** [comment]
登录我用的github的用户名还有密码，然后根据说明登录一直报 其他异常 Invalid argument，这个是后台返回的吗？

**Comment by CarGuo** [comment]
你试试下载的apk，这是网络请求如果没有匹配到定义好的code，就返回未知。
你看log看看是什么code

**Comment by zhangrurong8** [comment]
我刚试了下载的GSYGithubAppFlutter1.6.0-fix.apk,登录我的github也是报： 其他异常 Invalid argument。

**Comment by CarGuo** [comment]
那就很奇怪了，我这边是了两个github账号正常哇，你可以看看编译项目输出的http log，看看是 http 什么error

**Comment by zhangrurong8** [comment]
GSYGithubAppFlutter1.6.0-fix.apk,那请问一下上面的APK 可以用我的github账号登录吗？

**Comment by CarGuo** [comment]
可以啊，主要是你还是得看 http code 是什么。
我这边正常可以使用，你要不换个wifi 或者换个4G 试试

**Comment by zhangrurong8** [comment]
用wifi不可以，然后用了手机的4G就可以了，谢谢啊。
