### ISSUE TITLE
    [!] Unable to find a specification for `Reachability` depended upon by `connectivity`

### ISSUE THREAD

**Issue by Wanghuayin** [CarGuo/GSYGithubAppFlutter#47]
Pod install 的时候报了这个错误有什么解决办法吗？

**Comment by CarGuo** [comment]
你看配置那个issue

**Comment by Wanghuayin** [comment]
@CarGuo 试过了没有用。。。 很是奇怪

**Comment by Wanghuayin** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/13 这个是吗？

**Comment by Wanghuayin** [comment]
@CarGuo 我用的就是国外的。。。
![image](https://user-images.githubusercontent.com/15116717/44963824-a6344f00-af5f-11e8-820b-021b9e4761cb.png)

**Comment by CarGuo** [comment]
你的问题应该是connectivity这个库没找到，你是编译的ios报错吧···，

**Comment by Wanghuayin** [comment]
@CarGuo pod install 的时候报的
![image](https://user-images.githubusercontent.com/15116717/44964007-cf091400-af60-11e8-895d-98ea05b3dd99.png)

**Comment by CarGuo** [comment]
https://github.com/flutter/flutter/issues/14131

**Comment by Wanghuayin** [comment]
@CarGuo 最后请我们这边开发同学看了一下，最终解决
1、把podfile中 #use_frameworks! 这个注释掉，这个会引起Headers文件夹为空
2、删除了getversion插件的swift文件后，最终跑起来了。。。
![image](https://user-images.githubusercontent.com/15116717/44970985-86645180-af86-11e8-9d1b-27a75e2dc640.png)

**Comment by CarGuo** [comment]
good

**Comment by SylviaRu** [comment]
> 我们公司的是自己的源source,没有使用github的，reachablitiy是github的pod，所以需要使用github的源，我添加之后，就好了，reachablitiy会被添加到iOS的pods中

请问你添加了哪个源呢？我也遇到了同样的问题。
