### ISSUE TITLE
有没有打算集成各种第三方登录（微信、QQ、微博），或者其他OAuth2 授权

### ISSUE THREAD

**Issue by JL-Code** [CarGuo/GSYGithubAppFlutter#471]

**Comment by CarGuo** [comment]
github api 不支持啊问题是😂

**Comment by JL-Code** [comment]
> github api 不支持啊问题是😂

github 自己的 OAuth2 登录方式呢，我看到你的APP是直接输入账号密码的，可以走OAuth流程吗？

**Comment by CarGuo** [comment]
现在走的就是 OAuth 流程，只是不是 Web 网页模式下的那种，虽然是输入账号密码，但是实际上走的就是 OAuth。

你想要的大概就是打开的网页之后网页上登陆授权的，实质上没什么区别

**Comment by JL-Code** [comment]
> 现在走的就是 OAuth 流程，只是不是 Web 网页模式下的那种，虽然是输入账号密码，但是实际上走的就是 OAuth。
> 
> 你想要的大概就是打开的网页之后网页上登陆授权的，实质上没什么区别

我知道了你用的是Password模式。我期望的是授权码模式，我研究了下授权码模式在flutter 中的应用在授权服务器 返回code回来的那步没办法在webview 感知到（是我不知道怎么做），我看到一些解决方案：[在flutter app 内部开启一个http server 让授权服务器重定向到 flutter app开启的服务器里面 ](https://medium.com/@segaud.kevin/facebook-oauth-login-flow-with-flutter-9adb717c9f2e)。感觉这样的解决方案好奇怪。

**Comment by CarGuo** [comment]
流程是 首选需要 github 的授权最终会回调到 我们的服务器端，在我们服务器端就收到返回到 token 之后，跳转到我们自己页面， 然后就可以通过 js 回调到 Dart 中了。

**Comment by JL-Code** [comment]
> 流程是 首选需要 github 的授权最终会回调到 我们的服务器端，在我们服务器端就收到返回到 token 之后，跳转到我们自己页面H5页面， 然后就可以通过 js 回调到 Dart 中已经注册的方法。

看来还是得写一个H5页面。
最后一个问题：我想问下，因为微信或者微博都有提供SDK，那如果是使用 微信、微博它们的SDK来实现登录的话是不是得写Flutter Plugin 来分别对 iOS、Android来做开发。

**Comment by CarGuo** [comment]
如果你用 H5 做OAuth不用，如果你调起客户端的，必须这样了
