### ISSUE TITLE
你是怎样记录首页滚动位置的？

### ISSUE THREAD

**Issue by Cocomart** [CarGuo/GSYGithubAppFlutter#477]
我从内页返回到首页，发现切换到另一个tab页面再切回来，tab页面就被初始化了。但是再次切换tab又是可以保存位置的。
就好像每次从内页返回首页的时候，tab页面再切换时，都要重新build一次，才能保存滚动位置。这个你是怎么解决的？
刚入门的小白，代码没看懂，请教一下。

**Comment by CarGuo** [comment]
with AutomaticKeepAliveClientMixin 

bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context); // See AutomaticKeepAliveClientMixin.

**Comment by Cocomart** [comment]
实现了，感谢大神
