### ISSUE TITLE
关于图片缓存问题, informationCollector报错

### ISSUE THREAD

**Issue by YeFei572** [CarGuo/GSYGithubAppFlutter#480]
于是我将代码down下来, 发现一直报错
我的flutter是1.5.4稳定版的
![image](https://user-images.githubusercontent.com/26360338/60335552-cd697a80-99d0-11e9-9616-bdd97418c117.png)

**Comment by CarGuo** [comment]
看 readme ，用 beta 分支

**Comment by YeFei572** [comment]
稳定版不可以使用该功能吗?因为项目现在不敢用beta版, 烦请回答一下.

**Comment by CarGuo** [comment]
这是因为版本接口调整导致的，我们公司一直用着beta版本哦，因为稳定版太慢了，修复问题不及时，只要不是channel版本就好。

**Comment by YeFei572** [comment]
多谢
明白了
