### ISSUE TITLE
列表滑动卡顿

### ISSUE THREAD

**Issue by Dan-Humphrey** [CarGuo/GSYGithubAppFlutter#481]
小米9真机滑动列表明显卡顿（刚打开APP，放置一会就不卡了），下载的APK，看前面也有同样问题的同学，求解。。
当时学flutter的时候也写过列表，而且是很简单的显示text的item，同样能感觉到卡顿，很奇怪，网上搜了一下没有什么结论。

**Comment by CarGuo** [comment]
推测：
1、下拉刷新动画导致
2、列表卡片圆角
3、skia 机型兼容

这三个方面
