### ISSUE TITLE
能否解释一下哪段代码配置了app默认先跳到welcome.dart欢迎页

### ISSUE THREAD

**Issue by dengzhao7053** [CarGuo/GSYGithubAppFlutter#482]
一边看你的代码，一边学习flutter，有个问题需要请教，你的main.dart只有一段这样的代码：
routes: {
              WelcomePage.sName: (context) {
                store.state.platformLocale = Localizations.localeOf(context);
                return WelcomePage();
              },
              HomePage.sName: (context) {
                ///通过 Localizations.override 包裹一层，
                return new GSYLocalizations(
                    child: NavigatorUtils.pageContainer(new HomePage()));
              },
              LoginPage.sName: (context) {
                return new GSYLocalizations(
                    child: NavigatorUtils.pageContainer(new LoginPage()));
              },
            }
为什么这样就可以打开app后先跳欢迎页，不是很懂，麻烦解答一下

**Comment by CarGuo** [comment]
welcomepage.sname 是 / 代表着默认

**Comment by dengzhao7053** [comment]
好的 了解了 谢谢大佬
