### ISSUE TITLE
Dio Exception in response transformer handle .

### ISSUE THREAD

**Issue by HDHunter** [CarGuo/GSYGithubAppFlutter#489]
DioError [DioErrorType.DEFAULT]: type '_StreamHandlerTransformer<List<int>, List<int>>' is not a subtype of type 'StreamTransformer<Uint8List, List<int>>' of 'streamTransformer

`#1      DefaultTransformer.transformResponse (package:dio/src/transformer.dart:102:48)
    <asynchronous suspension>
    #2      Dio._makeRequest (package:dio/src/dio.dart:764:38)
    <asynchronous suspension>
    #3      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:703:22)
    #4      _rootRunUnary (dart:async/zone.dart:1132:38)
    #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
    #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
    #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
    #9      Future._complete (dart:async/future_impl.dart:473:7)
    #10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
    #11   `

在执行demo login 操作的时候，项目返回666异常，debug发现是 dio 处理response的一个异常，导致 responseResult为空。项目master使用的是,^2.1.4。有结局方案吗。

已经的response是201，body是 already added.

**Comment by CarGuo** [comment]
em····我刚刚试了下，可以正常登陆，没异常呢

**Comment by mgh644** [comment]
我也存在这个问题欸~

**Comment by mgh644** [comment]
模拟器不行，，，真机才可以
