### ISSUE TITLE
大佬请求一下，登录一直报401

### ISSUE THREAD

**Issue by leestars** [CarGuo/GSYGithubAppFlutter#492]
下载您的apk登录报401，我运行项目配置我申请的Client ID和Client Secret同样报401，我用的是用户名登录，账号也没有开启两步认证。请教一下这是为什么呢？

**Comment by CarGuo** [comment]
em·····这就很奇怪了，我试了我这边可以哇。

github 的 用户名和密码，要不你换个网络试试

**Comment by leestars** [comment]
> em·····这就很奇怪了，我试了我这边可以哇。
> 
> github 的 用户名和密码，要不你换个网络试试
我的锅，密码一直没输对
