### ISSUE TITLE
请教~

### ISSUE THREAD

**Issue by ylmyg** [CarGuo/GSYGithubAppFlutter#5]
想请教作者，想学习Flutter，该从哪方面学起，该看哪些书籍和网站，麻烦作者指点一下

**Comment by CarGuo** [comment]
一般从  https://flutterchina.club/get-started/install/ 这里开始，这个过程其实就是熟悉Dart语法和Flutter Api。

过程中主要看你原本的什么开发者，比如Android开发的、React开发者，上手都会比较容易，在语法熟悉上比较有优势。就我个人而言，简单熟悉Dart语法和Flutter API后，我会试着把自己的项目用Flutter重构一遍，这样在实践中学习。我个人推荐是花两三个小时熟悉通过上面的链接简单了解下，然后看别人的项目，最后动手。

目前GSYGithubApp系列的完成度都比较高，这个库后面也会配上一些文章说明，作为学习还是挺不错的。

**Comment by ylmyg** [comment]
作者你好，我是android开发者，目前公司要我学习前端开发，需要学习一种跨平台框架语言，我觉得Flutter不错，语言上比较熟悉，有个问题想请教，Flutter能支持web么？我看到文档上是支持web的，但是文中又是这样说明 Flutter是谷歌的移动UI框架，可以快速在iOS和Android上构建高质量的原生用户界面。不是很清楚是否支持web端的开发。

**Comment by CarGuo** [comment]
应该是说dart支持web，不过目前不是很流行就是了。
flutter不支持构建web，文档上的web是给web开发人员快速学习的对比。
所以公司如果让你学习前端的时候，还是学习下react或者vue吧。特别是vue是比较容易上手的。

**Comment by ylmyg** [comment]
主要是学习Vue有点困难，没有前端JS的基础，学习比较慢。我先把前端的基础知识先学习，慢慢过渡到Vue,Flutter得抽时间来学习，最后一个问题想问，没有IOS的基础，是否也能用Flutter开发，Flutter里面的控件是不是同时支持安卓和苹果上显示？

**Comment by CarGuo** [comment]
支持的，目前flutter在跨平台上兼容上是我用过最好的，主要是因为Flutter Engine和Skia，使得兼容效果很好，基本不需要什么ios基础
