### ISSUE TITLE
iOS，release模式下一直卡在闪屏下，Android的正常

### ISSUE THREAD

**Issue by Wanghuayin** [CarGuo/GSYGithubAppFlutter#50]
[VERBOSE-2:engine.cc(112)] Engine run configuration was invalid.
[        ] [VERBOSE-2:FlutterViewController.mm(411)] Could not launch engine with configuration.
![image](https://user-images.githubusercontent.com/15116717/44972823-1f966680-af8d-11e8-9bee-aaf2e754b7b1.png)

**Comment by CarGuo** [comment]
我刚打了个iphone6sp的ipa安装上了，没什么问题。

**Comment by CarGuo** [comment]
如下图
![giff](https://user-images.githubusercontent.com/10770362/44973690-fc20eb00-af8f-11e8-8ba5-f166411835e7.gif)

**Comment by CarGuo** [comment]
😂那就不是很清楚了，没重现问题。
