### ISSUE TITLE
账户登陆输入框不支持粘贴操作

### ISSUE THREAD

**Issue by rosuH** [CarGuo/GSYGithubAppFlutter#501]
1. 账户和密码输入框不支持密码管理器自动填充
2. 密码也不支持粘贴

... 使用 16 位乱序强密码，输入真的难受😣😂

**Comment by CarGuo** [comment]
密码不支持粘贴是正常的，但是 Android 上，官方现在除了 Android 0 版本支持账号密码自动填充外，貌似还没有统一支持框架吧？
