### ISSUE TITLE
功能要求

### ISSUE THREAD

**Issue by MostHated** [CarGuo/GSYGithubAppFlutter#506]
你好，
     如果这很难理解，我很抱歉，我正在使用谷歌翻译。 我非常感谢你为这个应用程序付出的所有工作，并将它发布给我们学习！ 最有帮助的一件事可能是将语言选择放在第一个登录屏幕上，至少在您第一次打开应用程序时。 我花了很长时间才承认最终找到它，因为我无法阅读菜单。

除此之外，应用程序上的工作非常棒，再次感谢！

-MH

**Comment by CarGuo** [comment]
Ok, thank you very much for your feedback. I will update it in the next version.

**Comment by CarGuo** [comment]
fix with 1.6.2
