### ISSUE TITLE
阅读源码不明白的地方，想学习下

### ISSUE THREAD

**Issue by TonyReet** [CarGuo/GSYGithubAppFlutter#513]
您好，阅读源码的时候，看到一个commitID:a5fcb346f52062f8daf9c26dbcd749d0231ae4dd，地址为:https://github.com/CarGuo/GSYGithubAppFlutter/commit/a5fcb346f52062f8daf9c26dbcd749d0231ae4dd
此提交的方法：_lockToAwait作用是什么呢，因为感觉直接return null 也可以，想问下是在哪种场景下面会出问题吗？谢谢

**Comment by TonyReet** [comment]
> 您好，阅读源码的时候，看到一个commitID:a5fcb346f52062f8daf9c26dbcd749d0231ae4dd，地址为:[a5fcb34](https://github.com/CarGuo/GSYGithubAppFlutter/commit/a5fcb346f52062f8daf9c26dbcd749d0231ae4dd)
> 此提交的方法：_lockToAwait作用是什么呢，因为感觉直接return null 也可以，想问下是在哪种场景下面会出问题吗？谢谢

相关代码

![图片.png](https://img12.360buyimg.com/img/jfs/t1/57904/19/5771/52467/5d37d0d0Eed09ea03/d992742102b6013c.png)

**Comment by CarGuo** [comment]
比如，某些场景下，下拉之后的页面只有两条数据，铺不满一页，然后马上会触发了加载更多，然后继续请求又新回来2条，这时候上下拉之间就需要一个lock等待的时序的问题。

甚至于你需要产生了下拉刷新和上拉加载更多，但是谁先谁后需要一个 lock 来保证时许
