### ISSUE TITLE
这是用了注释插件吗？

### ISSUE THREAD

**Issue by GanZhiXiong** [CarGuo/GSYGithubAppFlutter#514]
![image](https://user-images.githubusercontent.com/27394631/61766113-5201ba00-ae12-11e9-952f-2e6c0f7de9fa.png)
还是手动敲的注释？

**Comment by CarGuo** [comment]
这是我手动敲的，嘁嘁嘁···

**Comment by GanZhiXiong** [comment]
👍👍👍
