### ISSUE TITLE
flutter_lottie 安卓运行正常，iOS报错

### ISSUE THREAD

**Issue by shuaiwang007** [CarGuo/GSYGithubAppFlutter#515]
引入flutter_lottie, iOS运行报错，deployment Target设置为9.0
![屏幕快照 2019-07-25 上午9 59 14](https://user-images.githubusercontent.com/12870683/61840161-ddd31f00-aec2-11e9-89ef-d34f9e70055b.png)

**Comment by CarGuo** [comment]
更新下代码，这个去掉了

**Comment by shuaiwang007** [comment]
不用lottie动画了吗？使用的flutter_svg?  flutter_lottie目前是有什么问题吗？因为我们打算用flutter_lottie
😁

**Comment by CarGuo** [comment]
因为我用了 flutter flare

**Comment by shuaiwang007** [comment]
那我遇到的这个问题有解决思路吗？谢谢~

**Comment by CarGuo** [comment]
em····我是没遇到这个问题，看起来像是最低版本不同问题，你可以看看 podifle 和podspec 文件
