### ISSUE TITLE
cocoapods 报错

### ISSUE THREAD

**Issue by LwcXing** [CarGuo/GSYGithubAppFlutter#523]
Launching lib/main.dart on iPhone Xʀ in debug mode...
CocoaPods' output:
↳
    [!] Invalid `Podfile` file: invalid byte sequence in US-ASCII.
     #  from /Users/l_wcx/Desktop/我的代码/gitHub/GSYGithubAppFlutter/ios/Podfile:15
     #  -------------------------------------------
     #    File.foreach(file_abs_path) { |line|
     >        next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
     #        plugin = line.split(pattern=separator)
     #  -------------------------------------------
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile.rb:301:in `rescue in block in from_ruby'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile.rb:295:in `block in from_ruby'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile.rb:293:in `new'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile.rb:293:in `from_ruby'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile.rb:259:in `from_file'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/config.rb:199:in `podfile'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:45:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
Error output from CocoaPods:
↳
        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
        export LANG=en_US.UTF-8
        
Error running pod install
Error launching application on iPhone Xʀ.
Exited (sigterm)

**Comment by CarGuo** [comment]
pod 版本 1.6 系列现在

**Comment by LwcXing** [comment]
好吧，我的是1.7.5

**Comment by LwcXing** [comment]
什么时间能升级一下

**Comment by CarGuo** [comment]
这个是跟着 flutter sdk走的

**Comment by LwcXing** [comment]
OK

**Comment by CarGuo** [comment]
我还没有升级到 1.7.5 ，但是我记得 1.7.2 以下貌似都可以

**Comment by LwcXing** [comment]
我开始的是1.7.0 bata版的 都是不行的
我试试 降级

**Comment by CarGuo** [comment]
https://github.com/flutter/flutter/issues/36786

https://github.com/flutter/flutter/issues/14293

**Comment by LwcXing** [comment]
我把版本降级到1.7.2 还是一样 报错

**Comment by CarGuo** [comment]
你可以看看上面的链接，看看对你有没帮助

**Comment by LwcXing** [comment]
OK

**Comment by CarGuo** [comment]
目前我的环境的是 xcode 10.2.1 ， pod 1.6.1
