### ISSUE TITLE
showDialog(context) 和 CommonUtils.getLocale(context)不一致的问题

### ISSUE THREAD

**Issue by guangxingmao** [CarGuo/GSYGithubAppFlutter#524]
大佬，请教一个问题，showDialog(context: context)传的context 不能是最外层Page 这个widget的context,否则会报“No MaterialLocalizations found”，
但是CommonUtils.getLocale(context)，需要的是最外层Page这个widget的context,和Navigator.of(context).pop()一致，否则会报currentLocalized 为null，

所以在同时使用的时候，context的不一致，导致需要传递对应的context参数，有什么更优雅的方式吗？

**Comment by CarGuo** [comment]
我不是很理解你的说法，context 其实就是 Element ，像多语言的话，一般定出的   嵌套，通过 InheritedWidget 的特性，底层任何页面的 context 都可以通过封装后的 .of(context) 获取 。

至于 showDialog 的 MaterialLocalizations 也是 一样是 Localization ，都是基于顶层的 MaterialApp 去获取的。

**Comment by guangxingmao** [comment]
demo如下，点击按钮，弹出dialog,会报错误，"No MaterialLocalizations found"
![屏幕快照 2019-08-03 13 31 10](https://user-images.githubusercontent.com/19208420/62407940-01991200-b5f3-11e9-9f52-2c740b429842.png)
但是换种写法就没问题
![屏幕快照 2019-08-03 13 29 32](https://user-images.githubusercontent.com/19208420/62407945-17a6d280-b5f3-11e9-902c-1c1138449512.png)
![1564810196347](https://user-images.githubusercontent.com/19208420/62407946-19709600-b5f3-11e9-864a-d5401ebddecb.jpg)

**Comment by CarGuo** [comment]
因为你没加 Scafold

**Comment by guangxingmao** [comment]
![屏幕快照 2019-08-04 22 33 45](https://user-images.githubusercontent.com/19208420/62424942-03082e80-b708-11e9-9978-fa0597facb75.png)
外面套了一层 Scaffold 还是会报同样的错误

**Comment by CarGuo** [comment]
你要明白context  componentElement， RenderobjectElment的作用，还有showDialog的方法是什么，然后scaffold应该加的位置是哪里，并且scaffold加的时候，是哪里起到作用。这些源码里都有…
