### ISSUE TITLE
项目运行问题

### ISSUE THREAD

**Issue by Rob8it** [CarGuo/GSYGithubAppFlutter#53]
项目在UserDao.dart中缺少了一个类导致错误问题，以下报错
import 'package:gsy_github_app_flutter/common/config/ignoreConfig.dart';
"client_id": NetConfig.CLIENT_ID,
"client_secret": NetConfig.CLIENT_SECRET

是关于用户相关id参数报错问题！

**Comment by CarGuo** [comment]
请看readme
