### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by caoyunxiao** [CarGuo/GSYGithubAppFlutter#54]
IPhone 8p  跑起来，感觉还是有点卡顿

**Comment by CarGuo** [comment]
试试用release，debug是JIT的，肯定有卡顿

**Comment by shingohu** [comment]
有一个问题,应该是使用native View插件的共性问题,不知道大佬能否解决下
您使用了webview_plugin 发现侧滑返回无效(在appbar是可以的),这应该是个共性问题,由于native view是直接add进来,覆盖在flutter widget上面的,所以响应不了flutter的侧滑事件,有没有一个解决方案可以很好的解决此类问题,侧滑时可以整体返回,包括push进来也有动画

**Comment by CircleCurve** [comment]
關於這點, google大佬那邊已經開始有解決了 

[](https://github.com/flutter/flutter/issues/19030)
看一下他的commit 
`https://github.com/flutter/flutter/commits?author=amirh`
flutter_webview_plugin 是用android texture 去做的,  侧滑事件其實就是手勢問題, 這位google 大佬在fixed了, 目前他在搞ios inline view

![image](https://user-images.githubusercontent.com/8490834/48325332-076b5380-e670-11e8-9843-09eaae478079.png)

**Comment by CarGuo** [comment]
其实项目内我已经集成过androidView 也就是 inline view 测试了下，现在问题在于数据交互比较大的时候，其实效果并不是特别好，比如我在dart层到android层传输的是 html string的数据，到了android接收到再渲染成功，中间的空白期有点长，如果是纯url的话，其实还可以。
坐等后续更新

**Comment by shingohu** [comment]
@CircleCurve 看了下目前已经开源的WebView插件,发现实现方式大致有两种.一种是在原生端直接创建View,然后根据坐标进行覆盖再Flutter对应界面的位置。这种就是我说的无法响应手势,而且进出动画也没有,很突兀。 第二种就是通过启动一个原生的界面,这种就相当于启动一个Activity或者ViewController,上面说的手势和动画可以解决。第三种应该就是上面你说到的内嵌,这个我目前没有了解,好像之前一直不成熟吧

**Comment by CarGuo** [comment]
已经更新了项目，升级到了0.11.3的sdk支持下，目前测试了Android下可以正常使用Widget级别的WebView，也支持滑动效果。

具体在` CodeDetailPageWeb` 下使用的 ` WebView`，而 ` WebView` 在 **widget/webview/WebView.dart** 下

**Comment by CircleCurve** [comment]
@shingohu  webview 現在可以有內嵌了  Android 和IOS 都有了,  配合1.0 連GOOGLE MAP也實作了内嵌
