### ISSUE TITLE
项目无法克隆提示已被删除或移动什么原因

### ISSUE THREAD

**Issue by 319620ling** [CarGuo/GSYGithubAppFlutter#541]

**Comment by CarGuo** [comment]
？？？不会啊

**Comment by 319620ling** [comment]
那我多试试几次吧，用sourcetree试了3次都不行。

**Comment by 319620ling** [comment]
是这个地址吧https://github.com/CarGuo/GSYGithubAppFlutter.git为啥还是不行呢  奇怪，网速问题吗？

**Comment by CarGuo** [comment]
https://gitee.com/CarGuo/GSYGithubAppFlutter

不行你可以试试码云的

**Comment by 319620ling** [comment]
可以了  谢谢作者
