### ISSUE TITLE
401 登录不成功？

### ISSUE THREAD

**Issue by RainAndRain** [CarGuo/GSYGithubAppFlutter#549]

**Comment by RainAndRain** [comment]
unkown erro 422

**Comment by CarGuo** [comment]
下载的apk仅支持账号名和密码登录，不支持邮箱，然后如果422多了换个网络

**Comment by RainAndRain** [comment]
我直接 运行的项目在 ios 真机跑的  用邮箱密码登录  基本上 一直 422

**Comment by CarGuo** [comment]
直接运行得话，就是要看你配置的github id 和 secret 对不对，然后不要用邮箱，有用户名和密码。
有些时候申请的id和secret语言过一会生效。

**Comment by RainAndRain** [comment]
3q, let me try try
