### ISSUE TITLE
初始化gradle报错，不知道是不是gradle版本问题

### ISSUE THREAD

**Issue by wwbluechip** [CarGuo/GSYGithubAppFlutter#59]
![image](https://user-images.githubusercontent.com/24524783/45501558-16d73900-b7b4-11e8-9f78-a8ee87c17509.png)

![image](https://user-images.githubusercontent.com/24524783/45501534-0c1ca400-b7b4-11e8-9fea-681ecbb255e9.png)

**Comment by CarGuo** [comment]
看起来像是初始化的时候下载gralde超时
