### ISSUE TITLE
run失败

### ISSUE THREAD

**Issue by UTSOURCE** [CarGuo/GSYGithubAppFlutter#69]
![image](https://user-images.githubusercontent.com/14830459/45668411-3c1acd00-bb4f-11e8-9d68-7ad913d28e89.png)

**Comment by CarGuo** [comment]
看起来是你本地的环境问题

**Comment by UTSOURCE** [comment]
@CarGuo 我自己新建的可以正常运行，本地环境应该没有问题

**Comment by CarGuo** [comment]
你看log，gradle下打印下就知道。

**Comment by UTSOURCE** [comment]
我试试

**Comment by CarGuo** [comment]
你看下图，项目的文件是这样的

![5ba0a0d4e4b055bd5688207f](https://user-images.githubusercontent.com/10770362/45669404-9701f380-bb52-11e8-9fe9-9617ca62052a.jpg)

**Comment by UTSOURCE** [comment]
@CarGuo 
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 27

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.shuyu.gsygithub.gsygithubappflutter"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 13
        versionName "1.1.3"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }


    signingConfigs {
        debug {
            storeFile file("../gsygithubapp-debug.jks")
            storePassword "123456"
            keyAlias "debug"
            keyPassword "123456"
        }
        release {
            storeFile file("../gsygithubapp-debug.jks")
            storePassword "123456"
            keyAlias "debug"
            keyPassword "123456"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}

**Comment by UTSOURCE** [comment]
``def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 27

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.shuyu.gsygithub.gsygithubappflutter"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 13
        versionName "1.1.3"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }


    signingConfigs {
        debug {
            storeFile file("../gsygithubapp-debug.jks")
            storePassword "123456"
            keyAlias "debug"
            keyPassword "123456"
        }
        release {
            storeFile file("../gsygithubapp-debug.jks")
            storePassword "123456"
            keyAlias "debug"
            keyPassword "123456"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}

**Comment by UTSOURCE** [comment]
@CarGuo 我的不一样，我改下，在试试

**Comment by CarGuo** [comment]
额···不是下载的这个项目么···

**Comment by UTSOURCE** [comment]
是下载的这个项目，不知道怎么的不一样，奇怪了

**Comment by UTSOURCE** [comment]
@CarGuo 
![image](https://user-images.githubusercontent.com/14830459/45671712-c0be1900-bb58-11e8-8179-e460d0dcce3a.png)
这个情况怎么搞？

**Comment by UTSOURCE** [comment]
fanqiang可以解决吗

**Comment by UTSOURCE** [comment]
@CarGuo 新的错误
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Finished with error: FormatException: Bad UTF-8 encoding 0xc3 (at offset 152)
![image](https://user-images.githubusercontent.com/14830459/45672874-db45c180-bb5b-11e8-8e31-efd0ed547783.png)

**Comment by UTSOURCE** [comment]
@CarGuo ok了，谢谢！！！
