### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by jacktogitzxy** [CarGuo/GSYGithubAppFlutter#84]
时常出现网络请求422的情况

**Comment by CarGuo** [comment]
下载的App出现这个问题？

**Comment by CarGuo** [comment]
如果登陆正常，token没过期，难道是因为请求次数限制导致的？？

**Comment by CarGuo** [comment]
422 应该是Unprocessable Entity（错误实体）响应。

![image](https://user-images.githubusercontent.com/10770362/46786533-c083f880-cd67-11e8-8872-c076b31588cf.png)

**Comment by jacktogitzxy** [comment]
ok，了解了，谢谢
