### ISSUE TITLE
感觉流畅度不够

### ISSUE THREAD

**Issue by bacy** [CarGuo/GSYGithubAppFlutter#86]
不是传说比传统原生还流畅吗？
实际情况，三个app，flutter最差，首页滑动很明显卡顿

**Comment by CarGuo** [comment]
首先，你是编译的还是下载的app？
系统和机型是？
flutter在release和debug模式是AOT和JIT，流畅度差很多的。
目前我这边用的三个APP，flutter基本上的最流畅的。

**Comment by bacy** [comment]
> 我想我知道你想说的卡顿是什么原因，是因为页面切换第一次的时候会初始化，只能说这一块我处理的不够好。
> 初始化之后就好很多

我还没找到原因，用的是git上提供的二维码下载的app，手机是小米6.列表滑动明显对比其他两个有卡顿现象，页面切换也容易出现丢帧。

**Comment by bacy** [comment]
另外打开边界布局，可以看出weex的过度绘制非常严重，性能估计差reactnative很多

**Comment by CarGuo** [comment]
weex 确实不是很好。 
react-native 在升级到0.57.0 之后，flatlist的性能还行。
flutter目前确实我在三个项目中体验比较好的。

![如图](https://user-gold-cdn.xitu.io/2018/9/21/165fcc90c8d12598?imageView2/0/w/1280/h/960/ignore-error/1)
