### ISSUE TITLE
执行Packages Get 报错

### ISSUE THREAD

**Issue by puretsang** [CarGuo/GSYGithubAppFlutter#9]
clone下来，新建了ignoreConfig.dark  执行Packages get 
Because every version of flutter_test from sdk depends on analyzer 0.32.4 and json_serializable >=0.3.1+2 <0.5.3 depends on analyzer >=0.29.10 <0.32.0, flutter_test from sdk is incompatible with json_serializable >=0.3.1+2 <0.5.3.
So, because gsy_github_app_flutter depends on both json_serializable ^0.3.2 and flutter_test any from sdk, version solving failed.
pub get failed (1).
请问大神怎么解决？

**Comment by puretsang** [comment]
在国外不存在代理的问题。我在pubspec.yaml 这样改
  ```
pub_semver: ^1.3.6
  build_runner: ^0.7.6
  json_serializable: ^0.3.2
#  flutter_test:
#    sdk: flutter

```
同时删除test 包下widget_test.dart 项目成功跑起来

**Comment by CarGuo** [comment]
good job!
