### ISSUE TITLE
小的建议

### ISSUE THREAD

**Issue by wlkfec** [CarGuo/GSYGithubAppFlutter#94]
希望作者能够总结出一份项目的架构设计来，这样方便项目以及代码的学习，比如说数据管理的分类，哪些数据用Redux，而哪些数据在组件自身内部State管理各加格式，这样看起代码来更清晰。

**Comment by CarGuo** [comment]
好的，记下了

**Comment by CarGuo** [comment]
先有一个简单的

https://raw.githubusercontent.com/CarGuo/GSYGithubAppFlutter/master/framework.png

**Comment by CarGuo** [comment]
readme已补充
