### ISSUE TITLE
错误提示：缺少ignoreConfig.dart文件

### ISSUE THREAD

**Issue by asd8855** [CarGuo/GSYGithubAppFlutter#98]
Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  /Users/xxxx/Downloads/GSYGithubAppFlutter-master/lib/common/dao/UserDao.dart
...refers, in an import, to the following library:
  /Users/xxxx/Downloads/GSYGithubAppFlutter-master/lib/common/config/ignoreConfig.dart
Unfortunately, that library does not appear to exist on your file system.

**Comment by CarGuo** [comment]
请看readme和issue
